kevin-lee/effectie

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- .github/workflows/sbt-build.sh
- build.sbt
> Added: GitHub Actions

- README.md
Updated: `README.md` - status badge and minor fix
> Updated: README.md - status badge and minor fix

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build.sh
- build.sbt
Fixed: issues in build and release
> Fixed: issues in build and release

- build.sbt
- project/ProjectInfo.scala
> Cleaned up: project config

- README.md
- build.sbt
- scalaz-effect/src/main/scala/effectie/scalaz/ConsoleEffect.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
Close #17 - Support Scalaz Effect
> Close #17 - Support Scalaz Effect

- cats-effect/src/main/scala/effectie/cats/ConsoleEffect.scala
Task #16 - Add the instance of ConsoleEffect for Cats
> Task #16 - Add the instance of ConsoleEffect for Cats

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build.sh
- build.sbt
Fixed: wrongly configured release
> Fixed: wrongly configured release

- project/build.properties
> Upgraded: sbt 1.3.8 => 1.3.9

- cats-effect/src/main/scala/effectie/cats/ConsoleEffect.scala
- core/src/main/scala/effectie/ConsoleEffect.scala
- scalaz-effect/src/main/scala/effectie/scalaz/ConsoleEffect.scala
Close #24 - Add `putStr` and `putErrStr` to `ConsoleEffect`
> Close #24 - Add putStr and putErrStr to ConsoleEffect

- .github/workflows/release.yml
- changelogs/0.1.0.md
* Add common effectie types (#15)
* `EffectConstructor` and `Effectful`
* `ConsoleEffect` and `ConsoleEffectful`
* Support Cats Effect (#16)
* Instances of `EffectConstructor` and `ConsoleEffect` typeclasses
* `OptionTSupport` and `EitherTSupport` 
* Support Scalaz Effect (#17)
* Instances of `EffectConstructor` and `ConsoleEffect` typeclasses
* `OptionTSupport` and `EitherTSupport` 
* Add `putStr` and `putErrStr` to `ConsoleEffect` (#24)
> Effectie v0.1.0

- .github/workflows/publish-github-pages.yml
Fixed: ENV var name for GitHub token
> Fixed: ENV var name for GitHub token

- build.sbt
Changed: WartRemover is enabled in IDE but not in console
> Changed: WartRemover is enabled in IDE but not in console

- .github/workflows/release.yml
Enabled: Automatic deployment to Maven Central
> Enabled: Automatic deployment to Maven Central

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- core/src/main/scala/effectie/EffectConstructor.scala
- core/src/main/scala/effectie/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
Close #33 - Change `pureEffect` to `effectOfPure`
> Close #33 - Change pureEffect to effectOfPure

- changelogs/0.2.0.md
- docs/docs/docs/cats-effect/index.md
- docs/docs/docs/index.md
- docs/docs/docs/scalaz-effect/index.md
- project/ProjectInfo.scala
* Change `effectOfPure` to `effectOfPure` (#33)
> Effectie v0.2.0

- build.sbt
Fixed: `scalacOptions` for console - less strict
> Fixed: scalacOptions for console - less strict

- docs/docs/docs/cats-effect/console-effect.md
- docs/docs/docs/cats-effect/console-effectful.md
- docs/docs/docs/cats-effect/effect-constructor.md
- docs/docs/docs/cats-effect/effectful.md
- docs/docs/docs/cats-effect/eithert-support.md
- docs/docs/docs/cats-effect/index.md
- docs/docs/docs/cats-effect/optiont-support.md
- docs/docs/docs/scalaz-effect/console-effect.md
- docs/docs/docs/scalaz-effect/console-effectful.md
- docs/docs/docs/scalaz-effect/effect-constructor.md
- docs/docs/docs/scalaz-effect/effectful.md
- docs/docs/docs/scalaz-effect/eithert-support.md
- docs/docs/docs/scalaz-effect/index.md
- docs/docs/docs/scalaz-effect/optiont-support.md
- docs/microsite/data/menu.yml
* Updated: `effect-constructor.md` and `effectful.md` as well as `console-effect.md` and `console-effectful.md`
* Fixed: highlight in menu selection
* Fixed: titles
> Updated: docs

- docs/docs/docs/cats-effect/effect-constructor.md
- docs/docs/docs/scalaz-effect/effect-constructor.md
> Updated: docs - Fixed: broken links

- changelogs/0.3.0.md
- docs/docs/docs/index.md
- project/ProjectInfo.scala
* Change the names of `effect` constructor methods in `OptionTSupport` to `effectOf` (#40)
* Change the names of `effect` constructor methods in `EitherTSupport` to `effectOf` (#41)
> Effectie v0.3.0

- build.sbt
Changed: build.sbt - minor changes
> Changed: build.sbt - minor changes

- README.md
- docs/docs/index.md
Updated: docs - links in index pages
> Updated: docs - links in index pages

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- core/src/main/scala/effectie/EffectConstructor.scala
- core/src/main/scala/effectie/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
Close #50 - Change `unit` in `EffectConstructor` to `effectOfUnit`
> Close #50 - Change unit in EffectConstructor to effectOfUnit

- build.sbt
Updated: sbt config to aggregate sub-projects and ignore packaging the root
> Updated: sbt config to aggregate sub-projects and ignore packaging the root

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/task-template.md
Added: Task and bug ticket templates to create issue tickets
> Added: Task and bug ticket templates to create issue tickets

- project/build.properties
> Upgraded: sbt 1.3.9 => 1.3.10

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- core/src/main/scala/effectie/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
Close #56 - Add `EffectConstructor` for `Future` and `Id`
> Close #56 - Add EffectConstructor for Future and Id

- changelogs/0.4.0.md
- project/ProjectInfo.scala
* Change `unit` in `EffectConstructor` to `effectOfUnit` (#50)
* Add `EffectConstructor` for `Future` and `Id` (#56)
> Effectie v0.4.0

- docs/docs/docs/index.md
Updated: docs - new release info
> Updated: docs - new release info

- build.sbt
- cats-effect/src/main/scala/effectie/cats/Attempt.scala
- core/src/main/scala-2.11/effectie/compat/FutureCompat.scala
- core/src/main/scala-2.12_2.13/effectie/compat/FutureCompat.scala
- core/src/main/scala/effectie/Attempt.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Attempt.scala
> Close #60 - Add Attempt

- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
Close #68 - Improve EitherTSupport
> Close #68 - Improve EitherTSupport

- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
Close #70 - Improve `OptionTSupport`
> Close #70 - Improve OptionTSupport

- build.sbt
Changed: Scala 2.13 - 2.13.1 => 2.13.2
> Changed: Scala 2.13 - 2.13.1 => 2.13.2

- docs/docs/docs/cats-effect/eithert-support.md
- docs/docs/docs/cats-effect/index.md
- docs/docs/docs/cats-effect/optiont-support.md
- docs/docs/docs/scalaz-effect/eithert-support.md
- docs/docs/docs/scalaz-effect/index.md
- docs/docs/docs/scalaz-effect/optiont-support.md
Updated: docs for Effectie 1.0.0
> Updated: docs for Effectie 1.0.0

- .github/workflows/release.yml
Changed: GitHub Actions to publish to Maven Central in parallel
> Changed: GitHub Actions to publish to Maven Central in parallel

- .github/workflows/release.yml
Fixed: Bug in GitHub Actions to release Effectie (No more parallel)
> Fixed: Bug in GitHub Actions to release Effectie (No more parallel)

- docs/scalaz-effect/effect-constructor.md
- project/plugins.sbt
* Upgraded: sbt-docusaur 0.1.1 => 0.1.2
* Updated: docsUpgraded: sbt-docusaur 0.1.1 => 0.1.2
> Upgraded: sbt-docusaur 0.1.1 => 0.1.2

- website/src/pages/index.js
Updated: docs - title and description in `<head />`
> Updated: docs - title and description in <head />

- build.sbt
Changed: in build.sbt - String concatenation => String interpolation
> Changed: in build.sbt - String concatenation => String interpolation

- docs/cats-effect/eithert-support.md
- docs/scalaz-effect/eithert-support.md
- project/plugins.sbt
- website/docusaurus.config.js
- website/sidebars.js
- website/src/css/custom.css
* The container max width: 1140px => 1340px
* The sidebar is not collapsed by default
> Changed: doc site config

- project/plugins.sbt
Upgraded: sbt-docusaur 0.1.3 => 0.1.4
> Upgraded: sbt-docusaur 0.1.3 => 0.1.4

- build.sbt
- cats-effect/src/main/scala/effectie/cats/CanCatch.scala
- cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
- core/src/main/scala/effectie/CanCatch.scala
- core/src/test/scala-2.11_2.12/effectie/SomeControlThrowable.scala
- core/src/test/scala-2.13/effectie/SomeControlThrowable.scala
- core/src/test/scala/effectie/ExecutorServiceOps.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanCatch.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
Close #91 - Add `catchNonFatalEither` and `catchNonFatalEitherT` to `CanCatch`
> Close #91 - Add catchNonFatalEither and catchNonFatalEitherT to CanCatch

- cats-effect/src/main/scala/effectie/cats/Catching.scala
- cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Catching.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
Close #94 - Add `catchNonFatalEither` and `catchNonFatalEitherT` to `Catching`
> Close #94 - Add catchNonFatalEither and catchNonFatalEitherT to Catching

- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
- core/src/main/scala/effectie/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
Close #96 - Improve type inference in `Effectful`, `OptionTSupport` and `EitherTSupport`
> Close #96 - Improve type inference in Effectful, OptionTSupport and EitherTSupport

- cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
Added: Missing tests for `Catching` for `Id`
> Added: Missing tests for Catching for Id

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build.sh
- build.sbt
- core/src/main/scala/effectie/ConsoleEffect.scala
- project/plugins.sbt
* Scala `2.12.11` => `2.12.12` / `2.13.2` => `2.13.3`
* Changes as required by the new versions
> Upgraded: Scala

- README.md
> Updated: README.md - logo

- docs/getting-started.md
Updated: docs - with new version info
> Updated: docs - with new version info

- docs/cats-effect/can-catch.md
- docs/cats-effect/cats-effect.md
- docs/cats-effect/eithert-support.md
- docs/getting-started.md
- docs/scalaz-effect/eithert-support.md
- website/sidebars.js
* Updated: docs - with new version info
* Added: docs - `can-catch.md` (WIP)
* Changed: docs - `can-catch.md` - Amended: `CanCatch.catchNonFatal`
* Changed: docs - `can-catch.md` - Amended: `CanCatch.catchNonFatalEither`
* Changed: docs - `can-catch.md` - Amended: `CanCatch.catchNonFatalEitherT`
* Changed: docs - `can-catch.md` - Amended: `CanCatch.catchNonFatal`
* Changed: docs - `can-catch.md` - Amended: `CanCatch.catchNonFatalEither` and `CanCatch.catchNonFatalEitherT`
* Changed: docs - `can-catch.md` - Added: Catching
> Publish docs

- docs/scalaz-effect/can-catch.md
- website/sidebars.js
Added: `can-catch.md` for Scalaz and fix `can-catch.md` for Cats
> Added: can-catch.md for Scalaz and fix can-catch.md for Cats

- .github/workflows/build.yml
- .github/workflows/maven_central_sync.sh
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- build.sbt
Changed: build and release have been simplified and more restricted
> Changed: build and release have been simplified and more restricted

- .github/workflows/build.yml
- README.md
- docs/getting-started.md
> Fixed: build all

- project/plugins.sbt
> Added: sbt-updates

- cats-effect/src/main/scala/effectie/cats/CanHandleError.scala
- cats-effect/src/test/scala/effectie/cats/CanHandleErrorSpec.scala
- core/src/main/scala/effectie/CanHandleError.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanHandleError.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanHandleErrorSpec.scala
Close #116 - Add `CanHandleError[F[_]]`
> Close #116 - Add CanHandleError[F[_]]

- cats-effect/src/main/scala/effectie/cats/CanRecover.scala
- cats-effect/src/test/scala/effectie/cats/CanRecoverSpec.scala
- core/src/main/scala/effectie/CanRecover.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanRecover.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanRecoverSpec.scala
Close #118 - Add `CanRecover[F[_]]`
> Close #118 - Add CanRecover

- changelogs/1.3.0.md
- project/ProjectInfo.scala
* Add `CanHandleError` (#116)
* Add `CanRecover` (#118)
> Effectie v1.3.0

- build.sbt
- docs/getting-started.md
Automatically replace the versions in the doc site with the actual version from `build.sbt`
> Automatically replace the versions in the doc site with the actual version from build.sbt

- docs/getting-started.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgraded: Docusaurus 2.0.0-alpha.58 => 2.0.0-alpha.64
> Upgraded: Docusaurus 2.0.0-alpha.58 => 2.0.0-alpha.64

- cats-effect/src/main/scala/effectie/cats/FromFuture.scala
- cats-effect/src/test/scala/effectie/cats/ConcurrentSupport.scala
- cats-effect/src/test/scala/effectie/cats/FromFutureSpec.scala
> Close #124 - Add FromFuture

- cats-effect/src/main/scala/effectie/cats/ToFuture.scala
- cats-effect/src/test/scala/effectie/cats/ToFutureSpec.scala
> Close #125 - Add ToFuture

- cats-effect/src/main/scala/effectie/cats/Effectful.scala
- cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala/effectie/cats/CanHandleErrorSpec.scala
- cats-effect/src/test/scala/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
- core/src/main/scala/effectie/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanHandleErrorSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanRecoverSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
Close #128 - Add `Effectful` to the implementation projects
> Close #128 - Add Effectful to the implementation projects

- cats-effect/src/test/scala/effectie/cats/FromFutureSpec.scala
- cats-effect/src/test/scala/effectie/cats/ToFutureSpec.scala
Fixed: occasional build failures due to too short timeouts.
> Fixed: occasional build failures due to too short timeouts

- cats-effect/src/main/scala/effectie/cats/ConsoleEffectful.scala
- core/src/main/scala/effectie/ConsoleEffectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/ConsoleEffectful.scala
Close #130 - Add ConsoleEffectful to the implementation projects
> Close #130 - Add ConsoleEffectful to the implementation projects

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- cats-effect/src/main/scala/effectie/cats/Effectful.scala
- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- core/src/main/scala/effectie/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
Close #131 - Replace `effectOfPure` with `pureOf`
> Close #131 - Replace effectOfPure with pureOf

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- cats-effect/src/main/scala/effectie/cats/Effectful.scala
- core/src/main/scala/effectie/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
Close #134 - Replace `effectOfUnit` with `unitOf`
> Close #134 - Replace effectOfUnit with unitOf

- core/src/main/scala/effectie/ConsoleEffectful.scala
- core/src/main/scala/effectie/Effectful.scala
> Updated: deprecated messages

- cats-effect/src/test/scala/effectie/cats/FromFutureSpec.scala
- cats-effect/src/test/scala/effectie/cats/ToFutureSpec.scala
Fixed: Failed tests due to Future timeout
> Fixed: Failed tests due to Future timeout

- changelogs/1.4.0.md
- project/ProjectInfo.scala
* Add `FromFuture` (#124)
* Add `ToFuture` (#125)
* Add `Effectful` to the implementation projects (#128)
* Add `ConsoleEffectful` to the implementation projects (#130)
* Replace `effectOfPure` with `pureOf` (#131)
* Replace `effectOfUnit` with `unitOf` (#134)
> Effectie v1.4.0

- .github/workflows/build.yml
Updated: GitHub Actions build config
> Updated: GitHub Actions build config

- docs/cats-effect/can-catch.md
- docs/cats-effect/cats-effect.md
- docs/cats-effect/console-effect.md
- docs/cats-effect/effect-constructor.md
- docs/cats-effect/eithert-support.md
- docs/cats-effect/optiont-support.md
- docs/getting-started.md
- docs/scalaz-effect/can-catch.md
- docs/scalaz-effect/console-effect.md
- docs/scalaz-effect/effect-constructor.md
- docs/scalaz-effect/eithert-support.md
- docs/scalaz-effect/optiont-support.md
- docs/scalaz-effect/scalaz-effect.md
Updated: docs with newly updated info - the effect constructor for pure
> Updated: docs with newly updated info - the effect constructor for pure

- project/build.properties
> Upgraded: sbt 1.4.0 => 1.4.1

- .gitignore
Added: `.bsp/` to `.gitignore`
> Added: .bsp/ to .gitignore

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-alpha.64` => `2.0.0-alpha.66`
> Upgraded: Docusaurus 2.0.0-alpha.64 => 2.0.0-alpha.66

- project/plugins.sbt
Upgraded: `sbt-mdoc` `2.2.1` => `2.2.9` / `sbt-docusaur` `0.2.1` => `0.3.0`
> Upgraded: sbt-mdoc 2.2.1 => 2.2.9 / sbt-docusaur 0.2.1 => 0.3.0

- project/build.properties
> Upgraded: sbt 1.4.1 => 1.4.2

- changelogs/1.5.0.md
- project/ProjectInfo.scala
* Support Scala `3.0.0-M1` (#149)
> Effectie v1.5.0

- docs/getting-started.md
Updated: docs with supported Scala versions
> Updated: docs with supported Scala versions

- project/build.properties
Close #153 - Publish using sbt 1.3.13
> Close #153 - Publish using sbt 1.3.13

- build.sbt
Added: dottydoc option (`-siteroot` in `scalacOptions`)
> Added: dottydoc option (-siteroot in scalacOptions)

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- .gitignore
- changelogs/1.6.0.md
- project/ProjectInfo.scala
* Publish using sbt `1.3.13` (#153)
> Effectie v1.6.0

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- project/build.properties
Upgraded: sbt 1.3.13 => 1.4.3
* ENV Var: `SOURCE_DATE_EPOCH` - It's to set the timestamp for compiled files in the packaged artifacts
> Upgraded: sbt 1.3.13 => 1.4.3

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Added: dotty-docs creation to build script
> Added: dotty-docs creation to build script

- docs/cats-effect/can-handle-error.md
- website/sidebars.js
Updated: docs with `CanHandleError.handleNonFatal`
> Updated: docs with CanHandleError.handleNonFatal

- docs/cats-effect/from-future.md
- project/plugins.sbt
- website/sidebars.js
Updated: docs with `FromFuture.toEffect`
> Updated: docs with FromFuture.toEffect

- project/build.properties
> Upgraded: sbt 1.4.3 => 1.4.4

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
Close #161 - Support Scala `3.0.0-M2`
> Close #161 - Support Scala 3.0.0-M2

- changelogs/1.7.0.md
- project/ProjectInfo.scala
> Prepare to release v1.7.0

- build.sbt
- core/src/test/scala/effectie/ConcurrentSupport.scala
- effectie-monix/src/main/scala/effectie/monix/CanCatch.scala
- effectie-monix/src/main/scala/effectie/monix/CanHandleError.scala
- effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/Catching.scala
- effectie-monix/src/main/scala/effectie/monix/ConsoleEffect.scala
- effectie-monix/src/main/scala/effectie/monix/ConsoleEffectful.scala
- effectie-monix/src/main/scala/effectie/monix/EffectConstructor.scala
- effectie-monix/src/main/scala/effectie/monix/Effectful.scala
- effectie-monix/src/main/scala/effectie/monix/EitherTSupport.scala
- effectie-monix/src/main/scala/effectie/monix/FromFuture.scala
- effectie-monix/src/main/scala/effectie/monix/OptionTSupport.scala
- effectie-monix/src/main/scala/effectie/monix/ToFuture.scala
- effectie-monix/src/test/scala/effectie/monix/CanCatchSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanHandleErrorSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CatchingSpec.scala
- effectie-monix/src/test/scala/effectie/monix/FromFutureSpec.scala
- effectie-monix/src/test/scala/effectie/monix/ToFutureSpec.scala
Close #167 - Add Monix support
> Close #167 - Add Monix support

- .github/workflows/maven_central_sync.sh
- build.sbt
- effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
Close #167 - Add Monix support - with CI/CD config and fixed `CanRecover`
> Close #167 - Add Monix support - with CI/CD config and fixed CanRecover

- cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala/effectie/cats/CanHandleErrorSpec.scala
- cats-effect/src/test/scala/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
- cats-effect/src/test/scala/effectie/cats/EffectConstructorSpec.scala
- cats-effect/src/test/scala/effectie/cats/FromFutureSpec.scala
- cats-effect/src/test/scala/effectie/cats/ToFutureSpec.scala
- core/src/test/scala/effectie/ConcurrentSupport.scala
- effectie-monix/src/test/scala/effectie/monix/CanCatchSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanHandleErrorSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CatchingSpec.scala
- effectie-monix/src/test/scala/effectie/monix/EffectConstructorSpec.scala
- effectie-monix/src/test/scala/effectie/monix/FromFutureSpec.scala
- effectie-monix/src/test/scala/effectie/monix/ToFutureSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanHandleErrorSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanRecoverSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/EffectConstructorSpec.scala
* Added: more utilities to `ConcurrentSupport`
* Added more tests for Effectie support for Monix
* Added more tests for Effectie support for Cats Effect
* Added more tests for Effectie support for Scalaz Effect
* Clean up
> Add more tests and clean up

- changelogs/1.8.0.md
- project/ProjectInfo.scala
> Effectie v1.8.0

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Fixed: The wrong timestamps in the artifacts
> Fixed: Thw wrong timestamps in the artifacts

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #174 - Support Scala 3.0.0-M3
> Close #174 - Support Scala 3.0.0-M3

- project/build.properties
> Upgraded: sbt 1.4.4 => 1.4.5

- project/build.properties
> Upgraded: sbt 1.4.5 => 1.4.6

- .github/workflows/build-manual.yml
Added: Manual build trigger for GitHub Actions
> Added: Manual build trigger for GitHub Actions

- .github/workflows/build-manual.yml
Fixed: GitHub Actions manual build workflow name
> Fixed: GitHub Actions manual build workflow name

- .github/workflows/build-manual.yml
Fixed: The wrong condition to run the build on GitHub Actions - removed
> Fixed: The wrong condition to run the build on GitHub Actions - removed

- .github/workflows/manual-build.yml
* Changed: `build-manual.yml` => `manual-build.yml`
* Added: More description of one of the manual build params on GitHub Actions
> Add manual build param description

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/manual-maven-central-sync.yml
- .github/workflows/manual-publish.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
* Changed: Cache setup for GitHub Actions builds
* Added: Manual publish and maven central sync on GitHub Actions
> Change cache setup for GitHub Actions builds and Manual publish and maven central sync on GitHub Actions

- .github/workflows/manual-publish-github-pages.yml
Added: condition to run `build_and_publish_doc_site` - It should not be `gh-pages`.
> Added: condition to run build_and_publish_doc_site - It should not be gh-pages.

- project/build.properties
> Upgraded: sbt 1.4.6 => 1.4.7

- .github/workflows/make-docusaurus.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/manual-publish-github-pages.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Upgraded: `sbt-devoops` `1.0.3` => `2.0.0` and GitHub Actions config accordingly
> Upgraded: sbt-devoops 1.0.3 => 2.0.0 and GitHub Actions config accordingly

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #189 - Support Scala 3.0.0-RC1
> Close #189 - Support Scala 3.0.0-RC1

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- build.sbt
Close #191 - Upgrade Scala 2.13.3 to 2.13.4
> Close #191 - Upgrade Scala 2.13.3 to 2.13.4

- changelogs/1.9.0.md
- project/ProjectInfo.scala
* Upgrade Scala `2.13.3` to `2.13.4` (#191)
* Support Scala `3.0.0-RC1` (#189)
> Effectie v1.9.0

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-upload-artifacts-and-publish.yml
- .github/workflows/manual-maven-central-sync.yml
- .github/workflows/manual-publish.yml
More publish option in GitHub Actions
> More publish option in GitHub Actions

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/build.properties
Clean up and upgrade libs and sbt
> Clean up and upgrade libs and sbt

- .github/workflows/build.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/manual-github-upload-artifacts-and-publish.yml
- .github/workflows/manual-maven-central-sync.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- build.sbt
Updated: GitHub Actions config
> Updated: GitHub Actions config

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/ProjectInfo.scala
- project/plugins.sbt
Close #199 - Support Scala `3.0.0-RC3`
> Close #199 - Support Scala 3.0.0-RC3

- .github/workflows/build.yml
- .github/workflows/release.yml
Updated: GitHub Actions - release SNAPSHOT
> Updated: GitHub Actions - release SNAPSHOT

- build.sbt
> Updated: Project config

- build.sbt
- cats-effect/src/main/scala/effectie/cats/Catching.scala
- cats-effect/src/main/scala/effectie/cats/Effectful.scala
- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- effectie-monix/src/main/scala/effectie/monix/Catching.scala
- effectie-monix/src/main/scala/effectie/monix/Effectful.scala
- effectie-monix/src/main/scala/effectie/monix/EitherTSupport.scala
- effectie-monix/src/main/scala/effectie/monix/OptionTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Catching.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
Close #203 - Make partially applied type param types value class
> Close #203 - Make partially applied type param types value class

- core/src/main/scala/effectie/ConsoleEffect.scala
Close #205 - Add `readPassword` to `ConsoleEffect`
> Close #205 - Add readPassword to ConsoleEffect

- cats-effect/src/main/scala/effectie/cats/ConsoleEffectful.scala
- effectie-monix/src/main/scala/effectie/monix/ConsoleEffectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/ConsoleEffectful.scala
Close #207 - Add `readPassword` to `ConsoleEffectful`
> Close #207 - Add readPassword to ConsoleEffectful

- changelogs/1.10.0.md
* Support Scala `3.0.0-RC2` (#196)
* Support Scala `3.0.0-RC3` (#199)
* Make partially applied type param types value class (#203)
* Add `readPassword` to `ConsoleEffect` (#205)
* Add `readPassword` to `ConsoleEffectful` (#207)
> Effectie v1.10.0

- .github/workflows/build.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> Updated: doc config

- README.md
- build.sbt
- docs/getting-started.md
Updated: doc - get the latest version from git tag
> Updated: doc - get the latest version from git tag

- docs/cats-effect/can-catch.md
- docs/cats-effect/can-handle-error.md
- docs/cats-effect/cats-effect.md
- docs/cats-effect/console-effect.md
- docs/cats-effect/effect-constructor.md
- docs/cats-effect/eithert-support.md
- docs/cats-effect/from-future.md
- docs/cats-effect/optiont-support.md
- docs/getting-started.md
- docs/monix/can-catch.md
- docs/monix/can-handle-error.md
- docs/monix/console-effect.md
- docs/monix/effect-constructor.md
- docs/monix/eithert-support.md
- docs/monix/from-future.md
- docs/monix/monix.md
- docs/monix/optiont-support.md
- docs/scalaz-effect/can-catch.md
- docs/scalaz-effect/console-effect.md
- docs/scalaz-effect/effect-constructor.md
- docs/scalaz-effect/eithert-support.md
- docs/scalaz-effect/optiont-support.md
- website/docusaurus.config.js
- website/sidebars.js
Updated: docs
- Add docs for Effectie Monix
- minor changes in Cats Effect and Scalaz docs
> Updated: docs - Add docs for Effectie Monix

- .github/workflows/build.yml
- build.sbt
Close #215 - Support Scala 3.0.0
> Close #215 - Support Scala 3.0.0

- build.sbt
- docs/getting-started.md
> Update doc site

- build.sbt
- project/plugins.sbt
Upgraded: sbt-devoops `2.3.0` => `2.4.1`
> Upgraded: sbt-devoops 2.3.0 => 2.4.1

- project/build.properties
- project/plugins.sbt
Upgraded: sbt `1.5.2` => `1.5.3` / sbt-devoops `2.4.1` => `2.5.0`
> Upgraded: sbt 1.5.2 => 1.5.3 / sbt-devoops 2.4.1 => 2.5.0

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-alpha.74` => `2.0.0-beta.1`
> Upgraded: Docusaurus 2.0.0-alpha.74 => 2.0.0-beta.1

- website/package-lock.json
- website/package.json
Fixed: Doc site's vulnerabilities with `npm audit fix`.
> Fixed: Doc site's vulnerabilities with npm audit fix

- project/build.properties
- project/plugins.sbt
Upgraded: sbt and sbt plugins
- sbt `1.5.4` => `1.5.5`
- sbt-docusaur `0.5.0` => `0.6.0`
- sbt-devoops `2.5.0` => `2.6.0`
> Upgraded: sbt and sbt plugins

- cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
- cats-effect/src/test/scala/effectie/cats/EitherTSupportSpec.scala
- effectie-monix/src/main/scala/effectie/monix/EitherTSupport.scala
- effectie-monix/src/test/scala/effectie/monix/EitherTSupportSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala
- scalaz-effect/src/test/scala/effectie/scalaz/EitherTSupportSpec.scala
Close #230 - Add `EitherT` extension methods
> Close #230 - Add EitherT extension methods

- cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
- cats-effect/src/test/scala/effectie/cats/OptionTSupportSpec.scala
- effectie-monix/src/main/scala/effectie/monix/OptionTSupport.scala
- effectie-monix/src/test/scala/effectie/monix/OptionTSupportSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala
- scalaz-effect/src/test/scala/effectie/scalaz/OptionTSupportSpec.scala
Close #231 - Add `OptionT` extension methods
> Close #231 - Add OptionT extension methods

- cats-effect/src/main/scala/effectie/cats/EffectConstructor.scala
- cats-effect/src/main/scala/effectie/cats/Eft.scala
- effectie-monix/src/main/scala/effectie/monix/EffectConstructor.scala
- effectie-monix/src/main/scala/effectie/monix/Eft.scala
- effectie-monix/src/main/scala/effectie/monix/EitherTSupport.scala
- scalaz-effect/src/main/scala/effectie/scalaz/EffectConstructor.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Eft.scala
Clean up `Eft` and `EffectConstructor`
> Clean up Eft and EffectConstructor

- build.sbt
- docs/cats-effect/can-catch.md
- docs/cats-effect/can-handle-error.md
- docs/cats-effect/cats-effect.md
- docs/cats-effect/eithert-support.md
- docs/cats-effect/from-future.md
- docs/cats-effect/fx.md
- docs/cats-effect/optiont-support.md
- docs/getting-started.md
- docs/monix/can-catch.md
- docs/monix/can-handle-error.md
- docs/monix/eithert-support.md
- docs/monix/from-future.md
- docs/monix/fx.md
- docs/monix/monix.md
- docs/monix/optiont-support.md
- docs/scalaz-effect/can-catch.md
- docs/scalaz-effect/eithert-support.md
- docs/scalaz-effect/fx.md
- docs/scalaz-effect/optiont-support.md
- docs/scalaz-effect/scalaz-effect.md
- project/plugins.sbt
- website/sidebars.js
Updated: docs in accordance with the latest release
> Updated: docs in accordance with the latest release

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus to `2.0.0-beta.3`
> Upgraded: Docusaurus to 2.0.0-beta.3

- docs/getting-started.md
Updated: docs with the latest release info
> Updated: docs with the latest release info

- docs/cats-effect/cats-effect.md
- docs/monix/monix.md
- docs/scalaz-effect/scalaz-effect.md
Updated: docs with more `EitherTSupport` and `OptionTSupport` info
> Updated: docs with more EitherTSupport and OptionTSupport info

- .github/workflows/release.yml
Updated: GitHub Actions config for release
> Updated: GitHub Actions config for release

- changelogs/1.14.0.md
* Use Scala 3 syntax for `effectie-cats-effect` (#249)
* Use Scala 3 syntax for `effectie-cats-effect3` (#250)
> Effectie v1.14.0

- build.sbt
- test4cats/src/main/scala/effectie/testing/cats/Gens.scala
- test4cats/src/main/scala/effectie/testing/cats/Laws.scala
- test4cats/src/main/scala/effectie/testing/cats/MonadSpec.scala
- test4cats/src/main/scala/effectie/testing/cats/Specs.scala
Close #259 - Add project to test cats related code
> Close #259 - Add project to test cats related code

- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala/effectie/cats/MonadSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala/effectie/cats/LawsProperties.scala
- cats-effect3/src/test/scala/effectie/cats/MonadSpec.scala
- cats-effect3/src/test/scala/effectie/cats/Specs.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
- effectie-monix/src/test/scala/effectie/monix/FxSpec.scala
- effectie-monix/src/test/scala/effectie/monix/MonadSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Fx.scala
- scalaz-effect/src/test/scala/effectie/scalaz/FxSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/MonadSpec.scala
- scalaz-effect/src/test/scala/effectie/testing/Gens.scala
- scalaz-effect/src/test/scala/effectie/testing/Laws.scala
- scalaz-effect/src/test/scala/effectie/testing/Specs.scala
Close #256 - Make `Fx` `Monad`
> Close #256 - Make Fx Monad

- build.sbt
- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala/effectie/cats/MonadSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala/effectie/cats/MonadSpec.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
- effectie-monix/src/test/scala/effectie/monix/FxSpec.scala
- effectie-monix/src/test/scala/effectie/monix/MonadSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Fx.scala
- scalaz-effect/src/test/scala/effectie/scalaz/FxSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/MonadSpec.scala
- test4cats/src/main/scala/effectie/testing/cats/MonadSpec.scala
Close #265 - `Fx` should no longer be `Monad`
> Close #265 - Fx should no longer be Monad

- .scalafmt.conf
> Added: .scalafmt.conf

- .scalafmt.conf
Upgraded: Scalafmt `3.0.0-RC5` => `3.0.0`
> Upgraded: Scalafmt 3.0.0-RC5 => 3.0.0

- cats-effect/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect/src/main/scala-3/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanCatch.scala
- core/src/main/scala/effectie/CanCatch.scala
- effectie-monix/src/main/scala/effectie/monix/CanCatch.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanCatch.scala
Close #289 - More abstraction for `CanCatch`
> Close #289 - More abstraction for CanCatch

- cats-effect/src/main/scala-2/effectie/cats/syntax/error.scala
- cats-effect/src/main/scala-3/effectie/cats/syntax/error.scala
- cats-effect/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/syntax/error.scala
- cats-effect3/src/main/scala-3/effectie/cats/syntax/error.scala
- cats-effect3/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
- core/src/test/scala/effectie/testing/types.scala
- effectie-monix/src/main/scala/effectie/monix/syntax/error.scala
- effectie-monix/src/test/scala/effectie/monix/syntax/errorSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/syntax/error.scala
- scalaz-effect/src/test/scala/effectie/scalaz/syntax/errorSpec.scala
Close #277 - Add syntax for error handling
> Close #277 - Add syntax for error handling

- cats-effect/src/test/scala-2/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala-2/effectie/cats/CanHandleErrorSpec.scala
- cats-effect/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala-2/effectie/cats/CatchingSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/CanCatchSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/CatchingSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanCatchSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanHandleErrorSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CatchingSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanCatchSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CatchingSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanCatchSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanHandleErrorSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
- effectie-monix/src/test/scala/effectie/monix/CatchingSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanHandleErrorSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CanRecoverSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
> Clean up - re-use `SomeError`

- cats-effect/src/main/scala-2/effectie/cats/Effectful.scala
- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/Effectful.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect/src/test/scala-2/effectie/cats/EffectfulSpec.scala
- cats-effect/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/EffectfulSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/Effectful.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/Effectful.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/test/scala-2/effectie/cats/EffectfulSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/EffectfulSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala/effectie/cats/CatsEffectRunner.scala
- core/src/main/scala/effectie/CommonFx.scala
- core/src/test/scala/effectie/testing/tools.scala
- core/src/test/scala/effectie/testing/types.scala
- effectie-monix/src/main/scala/effectie/monix/Effectful.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
- effectie-monix/src/test/scala/effectie/monix/EffectfulSpec.scala
- effectie-monix/src/test/scala/effectie/monix/FxSpec.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Fx.scala
- scalaz-effect/src/test/scala/effectie/scalaz/EffectfulSpec.scala
- scalaz-effect/src/test/scala/effectie/scalaz/FxSpec.scala
Close #294 - Add `Fx.errorOf(Throwable)`
> Close #294 - Add Fx.errorOf(Throwable)

- cats-effect/src/main/scala-2/effectie/cats/CanHandleError.scala
- cats-effect/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-2/effectie/cats/Effectful.scala
- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/CanHandleError.scala
- cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-3/effectie/cats/Effectful.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanHandleError.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-2/effectie/cats/Effectful.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanHandleError.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-3/effectie/cats/Effectful.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- effectie-monix/src/main/scala/effectie/monix/CanHandleError.scala
- effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanHandleError.scala
- scalaz-effect/src/main/scala/effectie/scalaz/CanRecover.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Effectful.scala
- scalaz-effect/src/main/scala/effectie/scalaz/Fx.scala
> Make all inline final

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Updated: Docusaurus `2.0.0-beta.3` => `2.0.0-beta.6`
> Updated: Docusaurus 2.0.0-beta.3 => 2.0.0-beta.6

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-beta.6` => `2.0.0-beta.8`
> Upgraded: Docusaurus 2.0.0-beta.6 => 2.0.0-beta.8

- cats-effect/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect/src/main/scala-2/effectie/cats/Catching.scala
- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/CanCatch.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-2/effectie/cats/Catching.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanCatchSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala/effectie/cats/CatsEffectRunner.scala
- core/src/main/scala/effectie/CanCatch.scala
- core/src/main/scala/effectie/Fx.scala
- effectie-monix/src/main/scala/effectie/monix/CanCatch.scala
- effectie-monix/src/main/scala/effectie/monix/Catching.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
- effectie-monix/src/test/scala/effectie/monix/CanCatchSpec.scala
- effectie-monix/src/test/scala/effectie/monix/FxSpec.scala
Close #301 - Make `Fx` `CanCatch`
> Close #301 - Make Fx CanCatch

- .scalafmt.conf
Updated: `.scalafmt.conf` - `3.0.0` => `3.0.6`
> Updated: .scalafmt.conf - 3.0.0 => 3.0.6

- cats-effect/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect/src/main/scala-2/effectie/cats/CanHandleError.scala
- cats-effect/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect/src/main/scala-3/effectie/cats/CanCatch.scala
- cats-effect/src/main/scala-3/effectie/cats/CanHandleError.scala
- cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-3/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanHandleError.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanCatch.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanHandleError.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
- core/src/main/scala/effectie/CanCatch.scala
- core/src/main/scala/effectie/CanHandleError.scala
- core/src/main/scala/effectie/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/CanCatch.scala
- effectie-monix/src/main/scala/effectie/monix/CanHandleError.scala
- effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/Fx.scala
> Close #310 - Remove Xor

- cats-effect/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-2/effectie/cats/package.scala
- cats-effect/src/main/scala-2/effectie/cats/syntax/error.scala
- cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect/src/main/scala-3/effectie/cats/cats.scala
- cats-effect/src/main/scala-3/effectie/cats/syntax/error.scala
- cats-effect/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
- cats-effect/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-2/effectie/cats/package.scala
- cats-effect3/src/main/scala-2/effectie/cats/syntax/error.scala
- cats-effect3/src/main/scala-3/effectie/cats/CanRecover.scala
- cats-effect3/src/main/scala-3/effectie/cats/cats.scala
- cats-effect3/src/main/scala-3/effectie/cats/syntax/error.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
- core/src/main/scala/effectie/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
- effectie-monix/src/main/scala/effectie/monix/package.scala
- effectie-monix/src/main/scala/effectie/monix/syntax/error.scala
- effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
- effectie-monix/src/test/scala/effectie/monix/syntax/errorSpec.scala
Close #322 - `CanRecover` `trait` from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`
> Close #322 - `CanRecover` `trait` from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`

- .scalafmt.conf
- build.sbt
- cats-effect3/src/test/scala-2/effectie/cats/CanCatchSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanHandleErrorSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/CatchingSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/EffectfulSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxCtorSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-2/effectie/cats/ToFutureSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanCatchSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/CatchingSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/EffectfulSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxCtorSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/ToFutureSpec.scala
- cats-effect3/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
- cats-effect3/src/test/scala/effectie/cats/CatsEffectRunner.scala
Close #328 - Remove unused libraries for testing code using `cats-effect3`
> Close #328 - Remove unused libraries for testing code using cats-effect3

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
Add PR Labeler in GitHub Actions
> Add PR Labeler in GitHub Actions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/task-template.md
- .github/pr-labeler.yml
Add 'v2' label to issues and PRs
> Add 'v2' label to issues and PRs

- .github/pr-labeler.yml
Update: PR labeler config for documentation and publish-docs
> Update: PR labeler config for documentation and publish-docs

- .github/workflows/build.yml
- .github/workflows/sbt-build-all.sh
- .scalafmt.conf
- build.sbt
- project/plugins.sbt
Close #339 - Set up Codecov in GitHub Actions
> Close #339 - Set up Codecov in GitHub Actions

- build.sbt
- project/plugins.sbt
Close #342 - Publish to `s01.oss.sonatype.org` (the new Maven central)
> Close #342 - Publish to `s01.oss.sonatype.org` (the new Maven central)

- .github/workflows/release.yml
Add: upload test report to Codecov for the main branch
> Add: upload test report to Codecov for the main branch

- .github/workflows/release.yml
Fix: GitHub Actions to upload test report to Codecov in the main branch
> Fix: GitHub Actions to upload test report to Codecov in the main branch

- build.sbt
> Remove unused libraries

- .github/pr-labeler.yml
Update: PR labeler - `update` => `dependencies`
> Update: PR labeler - update => dependencies

- docs/cats-effect/cats-effect.md
- docs/getting-started.md
- docs/monix/monix.md
- docs/scalaz-effect/scalaz-effect.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade: docusaurus 2.0.0-beta.8 => 2.0.0-beta.14
> Upgrade: docusaurus 2.0.0-beta.8 => 2.0.0-beta.14

- .scalafmt.conf
Upgrade: `.scalafmt.conf` `3.3.1` => `3.4.0`
> Upgrade: .scalafmt.conf 3.3.1 => 3.4.0

- cats-effect/src/main/scala-2/effectie/cats/canCatch.scala
- cats-effect/src/main/scala-2/effectie/cats/canHandleError.scala
- cats-effect/src/main/scala-2/effectie/cats/canRecover.scala
- cats-effect/src/main/scala-2/effectie/cats/fx.scala
- cats-effect/src/main/scala-2/effectie/cats/fxCtor.scala
- cats-effect/src/test/scala-2/effectie/cats/fxSpec.scala
- cats-effect3/src/main/scala-2/effectie/cats/canCatch.scala
- cats-effect3/src/main/scala-2/effectie/cats/canHandleError.scala
- cats-effect3/src/main/scala-2/effectie/cats/canRecover.scala
- cats-effect3/src/main/scala-2/effectie/cats/fx.scala
- cats-effect3/src/main/scala-2/effectie/cats/fxCtor.scala
- effectie-monix/src/main/scala/effectie/monix/canCatch.scala
- effectie-monix/src/main/scala/effectie/monix/canHandleError.scala
- effectie-monix/src/main/scala/effectie/monix/canRecover.scala
- effectie-monix/src/main/scala/effectie/monix/fromFuture.scala
- effectie-monix/src/main/scala/effectie/monix/fx.scala
Close #371 - Uncapitalize typeclass instance names for Scala 2
> Close #371 - Uncapitalize typeclass instance names for Scala 2

- modules/effectie-monix/src/main/scala/effectie/monix/fx.scala
- modules/effectie-monix/src/main/scala/effectie/monix/fxCtor.scala
- modules/effectie-monix/src/main/scala/effectie/monix/toFuture.scala
Rename typeclass instances for monix (uncapitalize)
> Rename typeclass instances for monix (uncapitalize)

- .scalafmt.conf
Upgrade: .scalafmt.conf `3.4.0` => `3.4.3`
> Upgrade: .scalafmt.conf 3.4.0 => 3.4.3

- build.sbt
Close #377 - Upgrade cats to `2.7.0`
> Close #377 - Upgrade cats to 2.7.0

- codecov.yml
Add: `codecov.yml` - Add `modules/effectie-test4cats` to ignore
> Add: codecov.yml - Add modules/effectie-test4cats to ignore

- build.sbt
Close #388 - Support Scala.js - minor config changes
> Close #388 - Support Scala.js - minor config changes

- build.sbt
- version.sbt
effectie `v2.0.0-beta1` - set the version
> effectie v2.0.0-beta1 - set the version

- build.sbt
- version.sbt
Reset `version.sbt` - to `2.0.0-SNAPSHOT`
> Reset version.sbt - to 2.0.0-SNAPSHOT

- project/plugins.sbt
Upgrade: sbt-plugins
* sbt-devoops 2.16.0 => 2.19.0
* sbt-docusaur 0.8.0 => 0.10.0
> Upgrade: sbt-plugins

- project/plugins.sbt
Upgrade: `sbt-devoops` `2.19.0` => `2.22.0` / add `sbt-devoops-starter`
> Upgrade: sbt-devoops 2.19.0 => 2.22.0 / add sbt-devoops-starter

- .github/workflows/checks.yml
- project/plugins.sbt
Turn off scalafix check for Scala 3 since scalafix suppression for Scala 3 doesn't work
> Turn off scalafix check for Scala 3 since scalafix suppression for Scala 3 doesn't work

- website/docusaurus.config.js
Fix #415 - Upgrade docs site to Docusaurus 2.0.0-rc.1 - broken google analytics setup
> Fix #415 - Upgrade docs site to Docusaurus 2.0.0-rc.1 - broken google analytics setup

- build.sbt
Update: build.sbt - temporary fix for the project version in docs
> Update: build.sbt - temporary fix for the project version in docs

- build.sbt
- modules/effectie-monix/shared/src/main/scala/effectie/monix/fx.scala
- modules/effectie-monix/shared/src/main/scala/effectie/monix/fxCtor.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/canCatchSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/canHandleErrorSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/canRecoverSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/fxCtorSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/fxSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/monix/syntax/errorSpec.scala
- modules/effectie-monix/shared/src/test/scala/effectie/syntax/fxSpec.scala
Close #425 - Use `effectie-cats-effect` common code for `effectie-monix`
> Close #425 - Use `effectie-cats-effect` common code for `effectie-monix`

- project/plugins.sbt
Upgrade: `sbt-scalafix` `0.10.1` => `0.10.2`
> Upgrade: sbt-scalafix 0.10.1 => 0.10.2

- version.sbt
> Update: version.sbt

- project/build.properties
- project/plugins.sbt
Bump sbt and sbt plugins
- sbt `1.7.1` => `1.8.0`
- sbt-scoverage `1.9.2` => `2.0.6`
- sbt-coveralls `1.3.1` => `1.3.2`
- sbt-docusaur `0.10.0` => `0.12.0`
- sbt-devoops `2.22.0` => `2.23.0`
> Bump sbt and sbt plugins

- build.sbt
- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2Resource.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceSpec.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3Resource.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableFutureResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/UsingResource.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableFutureResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/data/TestErrors.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/data/TestResource.scala
Close #443 - Add `ReleasableResource` to automatically release resource after use
> Close #443 - Add `ReleasableResource` to automatically release resource after use

- .git-blame-ignore-revs
Update: `.git-blame-ignore-revs`
> Update: .git-blame-ignore-revs

- version.sbt
effectie v2.0.0-beta3 - Update `version.sbt`
> effectie v2.0.0-beta3 - Update `version.sbt`

- version.sbt
Update: version.sbt 2.0.0-beta3 => 2.0.0-SNAPSHOT
> Update: version.sbt 2.0.0-beta3 => 2.0.0-SNAPSHOT

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Update: GitHub Actions config - `olafurpg/setup-scala@v13` => `actions/setup-java@v3`
> Update: GitHub Actions config - olafurpg/setup-scala@v13 => actions/setup-java@v3

- modules/effectie-core/shared/src/main/scala/effectie/core/CanCatch.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/CanHandleError.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/CanRecover.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/ConsoleEffect.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/FromFuture.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/Fx.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/FxCtor.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/ToFuture.scala
Close #454 - Update missing implicit instance messages for Scala 3
> Close #454 - Update missing implicit instance messages for Scala 3

- version.sbt
Update: version.sbt 2.0.0-beta4 => back to 2.0.0-SNAPSHOT
> Update: version.sbt 2.0.0-beta4 => back to 2.0.0-SNAPSHOT

- website/package-lock.json
- website/package.json
Upgrade: Docusaurus `2.0.0-rc.1` => `2.2.0`
> Upgrade: Docusaurus `2.0.0-rc.1` => `2.2.0`

- project/plugins.sbt
Bump sbt-devoops `2.23.0` => `2.24.0` / sbt-docusaur `0.12.0` => `0.13.0`
> Bump sbt-devoops 2.23.0 => 2.24.0 / sbt-docusaur 0.12.0 => 0.13.0

- build.sbt
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/canCatchSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/canHandleErrorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/canRecoverSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/fxCtorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/testing/IoAppUtils.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/toFutureSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/syntax/errorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/syntax/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/canCatchSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/canHandleErrorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/canRecoverSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/fxCtorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/testing/IoAppUtils.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/toFutureSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/syntax/errorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/syntax/fxSpec.scala
- project/build.properties
Bump cats-effect `3.3.5` => `3.3.14` / extras `0.4.0` => `0.25.0`
> Bump cats-effect 3.3.5 => 3.3.14 / extras 0.4.0 => 0.25.0

- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2ResourceMaker.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceMakerSpec.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3ResourceMaker.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceMakerSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ResourceMaker.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/FutureResourceMakerSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ResourceMakerSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceMakerSpec.scala
Close #468 - Add `ResourceMaker`
> Close #468 - Add `ResourceMaker`

- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3Resource.scala
Minor update in importing `MonadCancelThrow`
> Minor update in importing `MonadCancelThrow`

- version.sbt
Update: version.sbt 2.0.0-beta5 => back to 2.0.0-SNAPSHOT
> Update: version.sbt 2.0.0-beta5 => back to 2.0.0-SNAPSHOT

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/manual-build.yml
- .gitignore
- build.sbt
- website/package-lock.json
- website/package.json
Upgrade: Docusaurus 2.2.0 => 2.3.0
> Upgrade: Docusaurus 2.2.0 => 2.3.0

- docs/latest/cats-effect2/cats-effect2.md
- docs/latest/cats-effect2/fx.md
> Update: docs for `Fx`

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Replace `docusaurus-lunr-search` with DocSearch (Algolia)
> Replace `docusaurus-lunr-search` with DocSearch (Algolia)

- docs/latest/cats-effect2/fx.md
- docs/latest/monix3/fx.md
Update: docs - `fx.md` with `pureOrError`
> Update: docs - `fx.md` with `pureOrError`

- version.sbt
Update: `version.sbt` `2.0.0-beta6` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta6 => back to 2.0.0-SNAPSHOT

- website/docusaurus.config.js
- website/src/pages/versions.js
> Update: docs - versions.js

- docs/latest/getting-started.md
Update: Docs - `getting-started.md` - add 'Why Effectie?'
> Update: Docs - `getting-started.md` - add 'Why Effectie?'

- build.sbt
- docs/latest/cats-effect2/fx/construct.md
- website/src/css/custom.css
Update: Docs - `construct.md` - with `unitOf`
- Also change the max width of the main container
> Update: Docs - construct.md - with unitOf

- .scalafmt.conf
- modules/effectie-cats-effect2/shared/src/test/scala-2/effectie/syntax/fxSpec.scala
- modules/effectie-cats-effect2/shared/src/test/scala-3/effectie/syntax/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/syntax/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/canHandleErrorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/canRecoverSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/syntax/fxSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/FxCtor.scala
- modules/effectie-core/shared/src/test/scala/effectie/core/FxCtorSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/core/FxSpec.scala
- modules/effectie-monix3/shared/src/test/scala/effectie/syntax/fxSpec.scala
- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/fx.scala
- modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/fx.scala
Close #488 - Add `pureOfSome`, `pureOfNone`, `pureOfRight` and `pureOfLeft` to `FxCtor` and `Fx`
> Close #488 - Add `pureOfSome`, `pureOfNone`, `pureOfRight` and `pureOfLeft` to `FxCtor` and `Fx`

- version.sbt
Update: `version.sbt` `2.0.0-beta7` => back to `2.0.0-SNAPSHOT`
> Update: `version.sbt` `2.0.0-beta7` => back to `2.0.0-SNAPSHOT`

- website/docusaurus.config.js
- website/src/pages/versions.js
Update: docs - `versions.js` with `2.0.0-beta6`
> Update: docs - `versions.js` with `2.0.0-beta6`

- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/error.scala
- modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/error.scala
Close #497 - Remove unused implicit params
> Close #497 - Remove unused implicit params

- modules/effectie-cats/shared/src/main/scala/effectie/instances/console.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/ConsoleFx.scala
- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/console.scala
- modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/console.scala
Close #499 - Rename `ConsoleEffect` to `ConsoleFx`
> Close #499 - Rename ConsoleEffect to ConsoleFx

- modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/canCatch.scala
- modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/fxCtor.scala
- modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/canCatch.scala
- modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/fxCtor.scala
- modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/canCatch.scala
- modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/fxCtor.scala
- modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/canCatch.scala
- modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/fxCtor.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/fxCtorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-2/effectie/instances/ce3/fxSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/fxCtorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/fxSpec.scala
- modules/effectie-cats/shared/src/main/scala/effectie/instances/id/canCatch.scala
- modules/effectie-cats/shared/src/main/scala/effectie/instances/id/fxCtor.scala
- modules/effectie-cats/shared/src/test/scala/effectie/specs/fxCtorSpec/FxCtorSpecs.scala
- modules/effectie-cats/shared/src/test/scala/effectie/specs/fxCtorSpec/IdSpecs.scala
- modules/effectie-cats/shared/src/test/scala/effectie/specs/fxSpec/FxSpecs.scala
- modules/effectie-cats/shared/src/test/scala/effectie/specs/fxSpec/IdSpecs.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/CanCatch.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/FxCtor.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/future/canCatch.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/future/fxCtor.scala
- modules/effectie-core/shared/src/test/scala/effectie/core/FxSpec.scala
- modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/canCatch.scala
- modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/fxCtor.scala
Close #501 - Move `flatMapFa` from `CanCatch` to `FxCtor`
> Close #501 - Move flatMapFa from CanCatch to FxCtor

- version.sbt
Update: `version.sbt` `2.0.0-beta8` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta8 => back to 2.0.0-SNAPSHOT

- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/canCatch.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/canHandleError.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/canRecover.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/fromFuture.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/fx.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/fxCtor.scala
- modules/effectie-core/shared/src/main/scala/effectie/instances/tries/toFuture.scala
- modules/effectie-core/shared/src/test/scala-2/effectie/instances/tries/fromFutureSpec.scala
- modules/effectie-core/shared/src/test/scala-2/effectie/instances/tries/toFutureSpec.scala
- modules/effectie-core/shared/src/test/scala-3/effectie/instances/tries/fromFutureSpec.scala
- modules/effectie-core/shared/src/test/scala-3/effectie/instances/tries/toFutureSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/tries/canCatchSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/tries/canHandleErrorSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/tries/canRecoverSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/tries/fxCtorSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/tries/fxSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/specs/fxCtorSpec/TrySpecs.scala
- modules/effectie-core/shared/src/test/scala/effectie/specs/fxSpec/TrySpecs.scala
Close #512 - Add `Fx` instance for `Try`
> Close #512 - Add Fx instance for Try

- .scalafmt.conf
- build.sbt
> Update: clean up config

- changelogs/2.0.0-beta9.md
- version.sbt
* Add `Fx` instance for `Try` - `Fx[Try]` (#512)
* Remove `cats` from the `core` module (#513)
* Reorganize tests (#515)
> effectie v2.0.0-beta9

- version.sbt
Update: `version.sbt` `2.0.0-beta9` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta9 => back to 2.0.0-SNAPSHOT

- website/docusaurus.config.js
- website/src/pages/versions.js
Update: docs with the latest version info
> Update: docs with the latest version info

- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2Resource.scala
- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2ResourceMaker.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceMakerSpec.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceSpec.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3Resource.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3ResourceMaker.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceMakerSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableFutureResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ResourceMaker.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/UsingResource.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/FutureResourceMakerSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableFutureResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ResourceMakerSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceMakerSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/data/TestResourceNoAutoClose.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/data/TestableResource.scala
Close #527 - Add `make[A](fa: => F[A])(release: A => F[Unit]): ReleasableResource[F, A]` to `ResourceMaker[F[*]]`
> Close #527 - Add `make[A](fa: => F[A])(release: A => F[Unit]): ReleasableResource[F, A]` to `ResourceMaker[F[*]]`

- codecov.yml
Update: `codecov.yml` - Add PR comment layout
> Update: `codecov.yml` - Add PR comment layout

- README.md
Update: `README.md` - Add Codecov test coverage graphs
> Update: `README.md` - Add Codecov test coverage graphs

- README.md
Update: `README.md` - Update badges
> Update: `README.md` - Update badges

- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2Resource.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceSpec.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3Resource.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableFutureResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/UsingResource.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableFutureResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
Close #542 - Add `ReleasableResource.pure`
> Close #542 - Add `ReleasableResource.pure`

- modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2Resource.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceSpec.scala
- modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3Resource.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableFutureResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-core/shared/src/main/scala/effectie/resource/UsingResource.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableFutureResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/resource/data/TestResource.scala
Close #544 - Add `ReleasableResource.map` and `ReleasableResource.flatMap`
> Close #544 - Add ReleasableResource.map and ReleasableResource.flatMap

- build.sbt
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceFunctorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceFunctorSpec.scala
- modules/effectie-cats/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-cats/shared/src/test/scala/effectie/resource/ReleasableResourceFunctorSpec.scala
Close #548 - Add `Functor` type-class for `ReleasableResource`
> Close #548 - Add `Functor` type-class for `ReleasableResource`

- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceApplicativeSpec.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceFunctorSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceApplicativeSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceFunctorSpec.scala
- modules/effectie-cats/shared/src/main/scala/effectie/resource/ReleasableResource.scala
- modules/effectie-cats/shared/src/main/scala/effectie/resource/ResourceMaker.scala
- modules/effectie-cats/shared/src/test/scala/effectie/resource/ReleasableResourceApplicativeSpec.scala
- modules/effectie-cats/shared/src/test/scala/effectie/resource/ReleasableResourceFunctorSpec.scala
- modules/effectie-cats/shared/src/test/scala/effectie/resource/UsingResourceMakerSpec.scala
Close #550 - Add `Applicative` type-class for `ReleasableResource`
> Close #550 - Add `Applicative` type-class for `ReleasableResource`

- version.sbt
Update: version.sbt `2.0.0-beta10` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt `2.0.0-beta10` => back to `2.0.0-SNAPSHOT`

- website/src/pages/versions.js
Update docs - add the previous version info to publish the current version doc
> Update docs - add the previous version info to publish the current version doc

- website/docusaurus.config.js
Update docs - Fix the current version
> Update docs - Fix the current version

- project/build.properties
> Upgrade sbt to 1.9.2

- version.sbt
Update: `version.sbt` `2.0.0-beta11` => back to `2.0.0-SNAPSHOT`
> Update: `version.sbt` `2.0.0-beta11` => back to `2.0.0-SNAPSHOT`

- project/build.properties
> Upgrade sbt to 1.9.3

- modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/CanRestartSpec.scala
- modules/effectie-cats-effect2/shared/src/test/scala/effectie/syntax/restartSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/CanRestartSpec.scala
- modules/effectie-cats-effect3/shared/src/test/scala/effectie/syntax/restartSpec.scala
- modules/effectie-core/shared/src/main/scala/effectie/core/CanRestart.scala
- modules/effectie-monix3/shared/src/test/scala/effectie/instances/monix3/CanRestartSpec.scala
- modules/effectie-monix3/shared/src/test/scala/effectie/syntax/restartSpec.scala
- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/all.scala
- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/error.scala
- modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/restart.scala
- modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/all.scala
- modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/restart.scala
Close #566 - Add `CanRestart` for retrying `F[A]`
> Close #566 - Add `CanRestart` for retrying `F[A]`

- .scalafmt.conf
> Bump scalafmt to 3.7.14

- docs/latest/cats-effect2/cats-effect2.md
- docs/latest/cats-effect2/console-fx.md
- docs/latest/cats-effect2/fx/_category_.json
- docs/latest/cats-effect2/import.md
Update: docs - a page to show what to import
> Update: docs - a page to show what to import

- docs/latest/cats-effect2/fx/error-handling/_category_.json
- docs/latest/cats-effect2/fx/error-handling/can-catch.md
- docs/latest/cats-effect2/fx/error-handling/can-handle-error.md
- docs/latest/cats-effect2/fx/fx-cheat-sheet.md
Update: docs - Add `fx-cheat-sheet.md`
> Update: docs - Add `fx-cheat-sheet.md`

- docs/latest/cats-effect2/fx/fx-cheat-sheet.md
Update: docs - add more to `fx-cheat-sheet.md`
> Update: docs - add more to `fx-cheat-sheet.md`

- docs/latest/cats-effect2/fx/fx-cheat-sheet.md
Update: docs - update `fx-cheat-sheet.md`
> Update: docs - update `fx-cheat-sheet.md`

- website/package-lock.json
- website/package.json
> Bump Docusaurus to `2.4.3`

- project/build.properties
> Bump sbt to `1.9.6`

- version.sbt
Update: version.sbt - reset to `2.0.0-SNAPSHOT`
> Update: version.sbt - reset to `2.0.0-SNAPSHOT`

- website/docusaurus.config.js
- website/src/pages/versions.js
Update docs - with the latest version info
> Update docs - with the latest version info

- website/src/pages/versions.js
- website/src/pages/versionsArchived.json
Update docs - move the archived versions to `versionsArchived.json`
> Update docs - move the archived versions to `versionsArchived.json`

- docs/latest/getting-started.md
Update: docs - getting started - add how to get for scala-cli
> Update: docs - getting started - add how to get for scala-cli

- build.sbt
Close #607 - Add `effectie-cats-effect2-time`
> Close #607 - Add `effectie-cats-effect2-time`

- modules/effectie-cats-effect2-time/shared/src/main/scala/effectie/instances/ce2/ClockBasedTimeSource.scala
- modules/effectie-cats-effect2-time/shared/src/test/scala/effectie/instances/ce2/ClockBasedTimeSourceSpec.scala
Close #608 - [`effectie-cats-effect2-time`] Add `TimeSource` with `Clock` from cats-effect 2
> Close #608 - [`effectie-cats-effect2-time`] Add `TimeSource` with `Clock` from cats-effect 2

- build.sbt
Close #610 - Add `effectie-cats-effect3-time`
> Close #610 - Add `effectie-cats-effect3-time`

- modules/effectie-cats-effect3-time/shared/src/main/scala/effectie/instances/ce3/ClockBasedTimeSource.scala
- modules/effectie-cats-effect3-time/shared/src/test/scala/effectie/instances/ce3/ClockBasedTimeSourceSpec.scala
Close #611 - [`effectie-cats-effect3-time`] Add `TimeSource` with `Clock` from cats-effect 3
> Close #611 - [`effectie-cats-effect3-time`] Add `TimeSource` with `Clock` from cats-effect 3

- version.sbt
Update: `version.sbt` - reset to `2.0.0-SNAPSHOT`
> Update: `version.sbt` - reset to `2.0.0-SNAPSHOT`

- .github/workflows/coverage.yml
- .github/workflows/release.yml
GitHub Actions: Add separate test coverage build (`coverage.yml`) with Codecov
> GitHub Actions: Add separate test coverage build (`coverage.yml`) with Codecov

- website/docusaurus.config.js
- website/src/pages/versionsArchived.json
Update docs with the latest version info
> Update docs with the latest version info

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- modules/effectie-cats/shared/src/test/scala/effectie/instances/id/fxSpec.scala
- modules/effectie-core/shared/src/test/scala/effectie/instances/future/fxSpec.scala
Fix #646 - Fix the broken test: `effectie.instances.future.fxSpec.FutureSpec.testFromEffectWithPure`
> Fix #646 - Fix the broken test: `effectie.instances.future.fxSpec.FutureSpec.testFromEffectWithPure`

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- build.sbt
- modules/effectie-cats/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
- project/plugins.sbt
GitHub Actions: Fix broken test coverage build
- Update Scala 2 version to 2.13.10 and bump sbt-wartremover and sbt-scoverage plugins
> GitHub Actions: Fix broken test coverage build
