cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala

Task #16 - Removed: unnecessary typeclass requirement in `EitherTSupport` and `OptionTSupport`

Task #16 - Removed: unnecessary typeclass requirement in EitherTSupport and OptionTSupport

---

cats-effect/src/main/scala/effectie/cats/OptionTSupport.scala
scalaz-effect/src/main/scala/effectie/scalaz/OptionTSupport.scala

Close #40 - Change the names of `effect` constructor methods in `OptionTSupport` to `effectOf`

Close #40 - Change the names of effect constructor methods in OptionTSupport to effectOf

---

cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala

Close #41 - Change the names of `effect` constructor methods in `EitherTSupport` to `effectOf`

Close #41 - Change the names of effect constructor methods in EitherTSupport to effectOf

---

.github/workflows/build.yml
.github/workflows/release.yml

* Build for Scala 2.11 => Java 8
* Build for Scala 2.12 and 2.13 => Java 11

Changed: Java version has been set in GitHub Actions

---

.github/workflows/release.yml

Different Java versions for different Scala versions when releasing
* Java 8 for Scala 2.11
* Java 11 for Scala 2.12
* Java 11 for Scala 2.13

GitHub Actions - different Java versions for different Scala versions when releasing

---

changelogs/1.0.0.md
docs/docs/docs/index.md
project/ProjectInfo.scala

This version contains some backward-incompatible changes in API (`EitherTSupport` and `OptionTSupport`).
* Add <code>~~Attempt~~</code> (#60)
* Change `Attempt` to `CanCatch` (#64)
* Add `Catching` (#62)
* Improve `EitherTSupport` (#68)
* Improve `OptionTSupport` (#70)

Effectie v1.0.0

---

cats-effect/src/main/scala/effectie/cats/CanCatch.scala
cats-effect/src/main/scala/effectie/cats/Catching.scala
core/src/main/scala-2.12_2.13/effectie/compat/FutureCompat.scala
core/src/main/scala/effectie/CanCatch.scala
scalaz-effect/src/main/scala/effectie/scalaz/CanCatch.scala
scalaz-effect/src/main/scala/effectie/scalaz/Catching.scala

Close #90 - `CanCatch.catchNonFatal` may not work due to non-lazy evaluation of `F[A]`
`CanCatch.catchNonFatal` now has a by-name parameter.

Close #90 - CanCatch.catchNonFatal may not work due to non-lazy evaluation of F[A]

---

changelogs/1.1.0.md
project/ProjectInfo.scala

* Add `catchNonFatalEither` and `catchNonFatalEitherT` to `CanCatch` (#91)
* Add `catchNonFatalEither` and `catchNonFatalEitherT` to `Catching` (#94)
* Improve type inference in `Effectful`, `OptionTSupport` and `EitherTSupport` (#96)
* `CanCatch.catchNonFatal` may not work due to non-lazy evaluation of `F[A]` (#90)
* Replace `master` branch with `main` branch (#78)
* Replace `sbt-microsites` with `Docusaurus 2` (#79)

Effectie v1.1.0

---

cats-effect/src/main/scala/effectie/cats/EitherTSupport.scala
scalaz-effect/src/main/scala/effectie/scalaz/EitherTSupport.scala

Close #104 - Improve type inference of `eitherTRight`, `eitherTRightPure`, `eitherTLeft` and `eitherTLeftPure` in `EitherTSupport`

Close #104 - Improve type inference of eitherTRight, eitherTRightPure, eitherTLeft and eitherTLeftPure in EitherTSupport

---

cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
core/src/main/scala/effectie/concurrent/ExecutorServiceOps.scala
scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala

Close #106 - Move `ExecutorServiceOps` from `test` to `main`

Close #106 - Move ExecutorServiceOps from test to main

---

cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
core/src/main/scala/effectie/concurrent/ExecutorServiceOps.scala
scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala

Close #108 - Add a way to log to `ExecutorServiceOps.shutdownAndAwaitTermination`

Close #108 - Add a way to log to ExecutorServiceOps.shutdownAndAwaitTermination

---

changelogs/1.2.0.md
project/ProjectInfo.scala

* Improve type inference of `eitherTRight`, `eitherTRightPure`, `eitherTLeft` and `eitherTLeftPure` in `EitherTSupport` (#104)
* Move `ExecutorServiceOps` from `test` to `main` (#106)
* Add a way to log to `ExecutorServiceOps.shutdownAndAwaitTermination` (#108)

Effectie v1.2.0

---

build.sbt
docs/getting-started.md

Updated: docs to have the supported Scala versions automatically when `docs/mdoc`

Updated: docs to have the supported Scala versions automatically when docs/mdoc

---

cats-effect/src/test/scala/effectie/cats/CanCatchSpec.scala
cats-effect/src/test/scala/effectie/cats/CanHandleErrorSpec.scala
cats-effect/src/test/scala/effectie/cats/CanRecoverSpec.scala
cats-effect/src/test/scala/effectie/cats/CatchingSpec.scala
cats-effect/src/test/scala/effectie/cats/EffectConstructorSpec.scala
cats-effect/src/test/scala/effectie/cats/FromFutureSpec.scala
cats-effect/src/test/scala/effectie/cats/ToFutureSpec.scala
core/src/test/scala/effectie/ConcurrentSupport.scala
effectie-monix/src/test/scala/effectie/monix/CanCatchSpec.scala
effectie-monix/src/test/scala/effectie/monix/CanHandleErrorSpec.scala
effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
effectie-monix/src/test/scala/effectie/monix/CatchingSpec.scala
effectie-monix/src/test/scala/effectie/monix/EffectConstructorSpec.scala
effectie-monix/src/test/scala/effectie/monix/FromFutureSpec.scala
effectie-monix/src/test/scala/effectie/monix/ToFutureSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CanCatchSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CanHandleErrorSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CanRecoverSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/CatchingSpec.scala
scalaz-effect/src/test/scala/effectie/scalaz/EffectConstructorSpec.scala

Changed: The factory method names in `ConcurrentSupport`

Changed: The factory method names in ConcurrentSupport

---

build.sbt
changelogs/1.8.1.md
project/ProjectInfo.scala

* Support Scala `3.0.0-M3` (#174)

Effectie v1.8.1

---

.github/workflows/manual-publish-github-pages.yml

Changed: auto-publishing the doc site is now manual - No need to keep the `publish-docs` branch

Changed: auto-publishing the doc site is now manual - No need to keep the publish-docs branch

---

.github/workflows/manual-publish-github-pages.yml

Changed: The name of GitHub Actions workflow: Publish GitHub Pages => Manual-Publish-GitHub-Pages

Changed: The name of GitHub Actions workflow: Publish GitHub Pages => Manual-Publish-GitHub-Pages

---

changelogs/1.11.0.md

* Support Scala `3.0.0` (#215)

Effectie v1.11.0

---

changelogs/1.12.0.md

* Add a shorter alternative name to `EffectConstructor` (#220)
* Rename `Eft` `Fx` (#234)
* Add `EitherT` extension methods (#230)
```scala
val fab: F[Either[A, B]] = ???
fab.eitherT // EitherT[F, A, B]
val ab: Either[A, B] = ???
ab.eitherT[F] // Either[F, A, B]
val fb: F[B] = ???
fb.rightT[A] // EitherT[F, A, B]
val b = ???
b.rightTF[F, A] // EitherT[F, A, B]
val fa: F[A] = ???
fa.leftT[B] // EitherT[F, A, B]
val a: A = ???
a.leftTF[F, B] // EitherT[F, A, B]
```
* Add `OptionT` extension methods (#231)
```scala
val foa: F[Option[A]] = ???
foa.optionT // OptionT[F, A]
val oa: Option[A] = ???
oa.optionT[F] // Option[F, A]
val fa: F[A] = ???
fa.someT OptionT[F, A] // OptionT[F, A]
val a = ???
a.someTF[F] // OptionT[F, A]
```
* `YesNo` in Scala 3 should derive `CanEqual` (#237)

Effectie v1.12.0

---

build.sbt
changelogs/1.13.0.md

* Drop Scala `2.11` support (#242)
* Support Cats Effect 3 (#229)

Effectie v1.13.0

---

cats-effect/src/test/scala-3/effectie/cats/CanCatchSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CatchingSpec.scala

Close #249 - Replace `sealed trait` based ADT with enum for Scala 3 in `effectie-cats-effect`

Close #249 - Replace sealed trait based ADT with enum for Scala 3 in effectie-cats-effect

---

cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
cats-effect/src/main/scala-3/effectie/cats/Catching.scala
cats-effect/src/main/scala-3/effectie/cats/ConsoleEffect.scala
cats-effect/src/main/scala-3/effectie/cats/Effectful.scala
cats-effect/src/main/scala-3/effectie/cats/EitherTSupport.scala
cats-effect/src/main/scala-3/effectie/cats/OptionTSupport.scala
cats-effect/src/main/scala-3/effectie/cats/ToFuture.scala
cats-effect/src/test/scala-3/effectie/cats/CanCatchSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CatchingSpec.scala
cats-effect/src/test/scala-3/effectie/cats/EffectConstructorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/EffectfulSpec.scala
cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
cats-effect/src/test/scala-3/effectie/cats/OptionTSupportSpec.scala
cats-effect/src/test/scala-3/effectie/cats/compat/CatsEffectIoCompatForFuture.scala

Fixed: Scala 2 `import` syntax to Scala 3's

Fixed: Scala 2 import syntax to Scala 3's

---

core/src/main/scala/effectie/CommonFx.scala

Close #257 - Fix `CommonFutureFx` to use `Future.successful` for `pureOf`

Close #257 - Fix CommonFutureFx to use Future.successful for pureOf

---

changelogs/1.15.0.md

* Fix `CommonFutureFx` to use `Future.successful` for `pureOf` (#257)
* Add project to test cats related code (#259)
* Add `FxCtor` as an alternative to `EffectConstructor` (#261)
* `Fx` should no longer be `Monad` (#265)
* There should be a way to test each `Monad` law instead of testing all the laws at once. (#266)
* ~~Make `Fx` `Monad` (#256)~~ (Undone in favor of #265)

Effectie v1.15.0

---

cats-effect/src/main/scala-2/effectie/cats/CanRecover.scala
cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
cats-effect3/src/main/scala-2/effectie/cats/CanRecover.scala
cats-effect3/src/main/scala-3/effectie/cats/CanRecover.scala
core/src/main/scala/effectie/CanRecover.scala
effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
scalaz-effect/src/main/scala/effectie/scalaz/CanRecover.scala

`xorT` and `xorT2FXor` no longer takes by-name params

xorT and xorT2FXor no longer takes by-name params

---

changelogs/1.16.0.md

* Add `catchNonFatalThrowable` (#274)
* Add syntax for error handling (#277)
* Add `AA >: A` to `catchNonFatalEither` and `catchNonFatalEitherT` (#279)
* Add `handleError` for `F[Xor[A, B]]` (#281)
* Add `recoverFrom` for `F[Xor[A, B]]` (#283)
* More abstraction for `CanRecover` (#284)
* More abstraction for `CanHandleError` (#287)
* More abstraction for `CanCatch` (#289)
* Add `Fx.errorOf(Throwable)` (#294)

Effectie v1.16.0 🎃

---

cats-effect/src/main/scala-2/effectie/cats/CanHandleError.scala
cats-effect/src/main/scala-2/effectie/cats/package.scala
cats-effect/src/main/scala-2/effectie/cats/syntax/error.scala
cats-effect/src/main/scala-3/effectie/cats/CanHandleError.scala
cats-effect/src/main/scala-3/effectie/cats/cats.scala
cats-effect/src/main/scala-3/effectie/cats/syntax/error.scala
cats-effect/src/test/scala-2/effectie/cats/CanHandleErrorSpec.scala
cats-effect/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
cats-effect3/src/main/scala-2/effectie/cats/CanHandleError.scala
cats-effect3/src/main/scala-2/effectie/cats/package.scala
cats-effect3/src/main/scala-2/effectie/cats/syntax/error.scala
cats-effect3/src/main/scala-3/effectie/cats/CanHandleError.scala
cats-effect3/src/main/scala-3/effectie/cats/cats.scala
cats-effect3/src/main/scala-3/effectie/cats/syntax/error.scala
cats-effect3/src/test/scala-2/effectie/cats/CanHandleErrorSpec.scala
cats-effect3/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
cats-effect3/src/test/scala-3/effectie/cats/CanHandleErrorSpec.scala
cats-effect3/src/test/scala-3/effectie/cats/syntax/errorSpec.scala
core/src/main/scala/effectie/CanHandleError.scala
effectie-monix/src/main/scala/effectie/monix/CanHandleError.scala
effectie-monix/src/main/scala/effectie/monix/package.scala
effectie-monix/src/main/scala/effectie/monix/syntax/error.scala
effectie-monix/src/test/scala/effectie/monix/CanHandleErrorSpec.scala
effectie-monix/src/test/scala/effectie/monix/syntax/errorSpec.scala

Issue #322 - Remove `CanHandleError` `trait` from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`

Issue #322 - Remove `CanHandleError` `trait` from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`

---

build.sbt
cats-effect/src/main/scala-2/effectie/cats/CanRecover.scala
cats-effect/src/main/scala-2/effectie/cats/Fx.scala
cats-effect/src/main/scala-3/effectie/cats/CanRecover.scala
cats-effect/src/main/scala-3/effectie/cats/Fx.scala
cats-effect/src/main/scala-3/effectie/cats/FxCtor.scala
cats-effect/src/test/scala-2/effectie/cats/FxSpec.scala
cats-effect/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
cats-effect/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
cats-effect/src/test/scala-3/effectie/cats/FxSpec.scala
cats-effect3/src/main/scala-2/effectie/cats/CanRecover.scala
cats-effect3/src/main/scala-2/effectie/cats/Fx.scala
cats-effect3/src/main/scala-3/effectie/cats/CanRecover.scala
cats-effect3/src/main/scala-3/effectie/cats/Fx.scala
cats-effect3/src/test/scala-2/effectie/cats/CanRecoverSpec.scala
cats-effect3/src/test/scala-2/effectie/cats/FxSpec.scala
cats-effect3/src/test/scala-2/effectie/cats/syntax/errorSpec.scala
cats-effect3/src/test/scala-3/effectie/cats/CanRecoverSpec.scala
cats-effect3/src/test/scala-3/effectie/cats/FxSpec.scala
core/src/main/scala/effectie/CanRecover.scala
core/src/main/scala/effectie/Fx.scala
effectie-monix/src/main/scala/effectie/monix/CanRecover.scala
effectie-monix/src/main/scala/effectie/monix/Fx.scala
effectie-monix/src/test/scala/effectie/monix/CanRecoverSpec.scala
effectie-monix/src/test/scala/effectie/monix/FxSpec.scala
effectie-monix/src/test/scala/effectie/monix/syntax/errorSpec.scala

Close #303 - Make `Fx` `CanRecover`

Close #303 - Make Fx CanRecover

---

.scalafmt.conf

Update: `.scalafmt.conf` - Add align token for `->`

Update: .scalafmt.conf - Add align token for ->

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
website/package.json

Upgrade: docusaurus `2.0.0-beta.14` => `2.0.0-beta.20` (can't be published until effectie v2 is released)

Upgrade: docusaurus `2.0.0-beta.14` => `2.0.0-beta.20` (can't be published until effectie v2 is released)

---

changelogs/2.0.0-beta2.md
version.sbt

Rename modules and packages (#430)
* `effectie-cats` => `effectie-syntax`
* `effectie-cats-effect` => `effectie-cats-effect2`
* `effectie-cats-effect3` remains the same
* `effectie-monix` => `effectie-monix3`
* Cats Effect 2: `effectie.cats` => `effectie.ce2`
* Cats Effect 3: `effectie.cats` => `effectie.ce3`
* Monix 3: `effectie.monix` => `effectie.monix3`
***
* Use `effectie-cats-effect` common code for `effectie-monix` (#425)
***
* Add `FxCtor.pureOrError(a)` and `Fx.pureOrError(a)` (#424)
```scala
FxCtor[IO].pureOrError(1)
// IO[Int] = Pure(1)
FxCtor[IO].pureOrError[Int]((throw new RuntimeException("ERROR")): Int)
// IO[Int] = RaiseError(java.lang.RuntimeException("ERROR"))
```
***
* Clean up syntax (#421)
* syntax should have cats (#432)
* (`effectie.cats.syntax` and …

effectie v2.0.0-beta2

---

changelogs/2.0.0-beta3.md

* Reorganize instances - move to `effectie.instances` (#429)
* `effectie.instances.future`
* `effectie.instances.ce2`
* `effectie.instances.ce3`
* `effectie.instances.monix3`
* `effectie.instances.id`
* move to `effectie.instances`: Move instances for `Future` to `effectie.instances.future`
* Also add `@implicitNotFound` to show what to import
* move to `effectie.instances`: Move instances for `Id` to `effectie.instances.id`
* Remove instances for `Id` for Cats Effect 2 and 3 since they are now in the `effectie-cats`
* Move `ConsoleEffect` instance to `effectie.instances`
* Also `effectie.instances.future.fromFuture.FromFutureToIdTimeout` => `effectie.core.FromFuture.FromFutureToIdTimeout`
* Remove instances for `Id` for Monix since they are now in the `effectie-cats`
* Remove instances …

effectie v2.0.0-beta3

---

modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/canCatch.scala
modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/fx.scala
modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/canCatch.scala
modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/fx.scala
modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/canCatch.scala
modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/fx.scala
modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/canCatch.scala
modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/fx.scala
modules/effectie-cats/shared/src/main/scala/effectie/instances/id/canCatch.scala
modules/effectie-cats/shared/src/main/scala/effectie/instances/id/fx.scala
modules/effectie-core/shared/src/main/scala/effectie/core/CanCatch.scala
modules/effectie-core/shared/src/main/scala/effectie/instances/future/canCatch.scala
modules/effectie-core/shared/src/test/scala/effectie/resource/ReleasableResourceSpec.scala
modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
modules/effectie-core/shared/src/test/scala/effectie/testing/types.scala
modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/canCatch.scala
modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/fx.scala
modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/error.scala
modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/error.scala

Close #457 - Change `f` in `def catchNonFatal[A, B](fb: => F[B])(f: Throwable => A): F[Either[A, B]]` to `f: PartialFunction[Throwable, AA]`

Close #457 - Change `f` in `def catchNonFatal[A, B](fb: => F[B])(f: Throwable => A): F[Either[A, B]]` to `f: PartialFunction[Throwable, AA]`

---

changelogs/2.0.0-beta4.md
version.sbt

* Update missing implicit instance messages for Scala 3 (#454)
e.g.)
```scala
import effectie.instances.ce2.fx.*
```
to
```scala
import effectie.instances.ce2.fx.given
```
* Change `f` in `def catchNonFatal[A, B](fb: => F[B])(f: Throwable => A): F[Either[A, B]]` to `f: PartialFunction[Throwable, AA]` (#457)
```scala
CanCatch[F].catchNonFatal(fa) {
case FooException(err) =>
FooError(err)
}
// If fa throws FooException, the result is F[Either[FooError, A]]
// If fa throws some other exception, the result is F[Either[FooError, A]] but it's actually the same as errorOf[Either[FooError, A]](theException) so the exception is not caught in Either.
```

effectie v2.0.0-beta4

---

changelogs/2.0.0-beta5.md
version.sbt

* Add `ResourceMaker` (#468)
```scala
ResourceMaker[F].forAutoCloseable[A <: AutoCloseable](fa: F[A]): ReleasableResource[F, A]
```
```scala
import effectie.resource.ResourceMaker
ResourceMaker.usingResourceMaker // ResourceMaker[Try]
ResourceMaker.futureResourceMaker(implicit ec: ExecutionContext) // ResourceMaker[Future]
```
```scala
import effectie.resource.Ce2ResourceMaker
Ce2ResourceMaker.forAutoCloseable // ResourceMaker[F] where F[*]: Sync: BracketThrow
```
```scala
import effectie.resource.Ce3Resource
Ce3Resource.forAutoCloseable // ResourceMaker[F] where F[*]: Sync: MonadCancelThrow
```
* `cats-effect` `3.3.5` => `3.3.14`

effectie v2.0.0-beta5

---

modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/canCatch.scala
modules/effectie-cats-effect2/shared/src/main/scala-2/effectie/instances/ce2/fx.scala
modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/canCatch.scala
modules/effectie-cats-effect2/shared/src/main/scala-3/effectie/instances/ce2/fx.scala
modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/canCatch.scala
modules/effectie-cats-effect3/shared/src/main/scala-2/effectie/instances/ce3/fx.scala
modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/canCatch.scala
modules/effectie-cats-effect3/shared/src/main/scala-3/effectie/instances/ce3/fx.scala
modules/effectie-cats/shared/src/main/scala/effectie/instances/id/canCatch.scala
modules/effectie-cats/shared/src/main/scala/effectie/instances/id/fx.scala
modules/effectie-core/shared/src/main/scala/effectie/core/CanCatch.scala
modules/effectie-core/shared/src/main/scala/effectie/instances/future/canCatch.scala
modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceMakerSpec.scala
modules/effectie-core/shared/src/test/scala/effectie/resource/UsingResourceSpec.scala
modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/canCatch.scala
modules/effectie-monix3/shared/src/main/scala/effectie/instances/monix3/fx.scala

Close #480 - Remove `implicit fxCtor: FxCtor[F]` param from the catch methods in `CanCatch`

Close #480 - Remove implicit fxCtor: FxCtor[F] param from the catch methods in CanCatch

---

changelogs/2.0.0-beta6.md
version.sbt

* Remove `implicit fxCtor: FxCtor[F]` param from the catch methods in `CanCatch` (#480)
The following methods in `CanCatch`
```scala
def catchNonFatal[A, B](
fb: => F[B]
)(
f: PartialFunction[Throwable, A]
)(
implicit fxCtor: FxCtor[F]
): F[Either[A, B]]
def catchNonFatalEither[A, AA >: A, B](
fab: => F[Either[A, B]]
)(
f: PartialFunction[Throwable, AA]
)(
implicit fxCtor: FxCtor[F]
): F[Either[AA, B]] 
```
have been changed to
```scala
def catchNonFatal[A, B](
fb: => F[B]
)(
f: PartialFunction[Throwable, A]
): F[Either[A, B]]
def catchNonFatalEither[A, AA >: A, B](
fab: => F[Either[A, B]]
)(
f: PartialFunction[Throwable, AA]
): F[Either[AA, B]] 
```

effectie v2.0.0-beta6

---

modules/effectie-core/shared/src/main/scala/effectie/core/CanCatch.scala
modules/effectie-core/shared/src/main/scala/effectie/core/CanHandleError.scala
modules/effectie-core/shared/src/main/scala/effectie/core/CanRecover.scala
modules/effectie-core/shared/src/main/scala/effectie/core/ConsoleEffect.scala
modules/effectie-core/shared/src/main/scala/effectie/core/FromFuture.scala
modules/effectie-core/shared/src/main/scala/effectie/core/FxCtor.scala
modules/effectie-core/shared/src/main/scala/effectie/core/ToFuture.scala
modules/effectie-core/shared/src/main/scala/effectie/core/compileTimeMessages.scala

Close #489 - Fix typo in the missing implicit instance messages and update the messages to use instances of `Fx` instead of others

Close #489 - Fix typo in the missing implicit instance messages and update the messages to use instances of Fx instead of others

---

docs/latest/cats-effect2/fx/construct.md

Update: docs - `construct.md`: fix typo

Update: docs - `construct.md`: fix typo

---

changelogs/2.0.0-beta7.md
version.sbt

* Add `pureOfOption`, `pureOfSome`, `pureOfNone`, `pureOfRight` and `pureOfLeft` to `FxCtor` and `Fx` (#488)
* `Fx[F].pureOfOption[A](a: A): F[Option[A]]`
* `Fx[F].pureOfSome[A](a: A): F[Option[A]]`
* `Fx[F].pureOfNone[A]: F[Option[A]]`
* `Fx[F].pureOfRight[A][B](b: B): F[Either[A, B]]`
* `Fx[F].pureOfLeft[B][A](a: A): F[Either[A, B]]`
* Fix typo in the missing `implicit` instance messages (#489)

effectie v2.0.0-beta7

---

modules/effectie-core/shared/src/main/scala/effectie/core/ConsoleFx.scala

Issue #499 - Fix missing `implicit` instance message for `ConsoleFx`

Issue #499 - Fix missing `implicit` instance message for `ConsoleFx`

---

modules/effectie-core/shared/src/main/scala/effectie/core/ConsoleFx.scala

Close #504 - Move `FxCtor` from instance creation of `ConsoleFx` to each `ConsoleFx` method param

Close #504 - Move `FxCtor` from instance creation of `ConsoleFx` to each `ConsoleFx` method param

---

changelogs/2.0.0-beta8.md
version.sbt

* Remove unused implicit params (#497)
```scala
def catchNonFatal[A](
f: PartialFunction[Throwable, A]
)(
implicit canCatch: CanCatch[F],
fxCtor: FxCtor[F], // <= This is unused
): F[Either[A, B]] =
canCatch.catchNonFatal[A, B](fb())(f)
```
The `implicit` param `fxCtor: FxCtor[F]` has been removed.
* Rename `ConsoleEffect` to `ConsoleFx` (#499)
* Move `flatMapFa` from `CanCatch` to `FxCtor` (#501)
```scala
def flatMapFa[A, B](fa: F[A])(f: A => F[B]): F[B]
```
* Move `FxCtor` from instance creation of `ConsoleFx` to each `ConsoleFx` method param (#504)
```scala
implicit def consoleFxF[F[*]: FxCtor: FlatMap]: ConsoleFx[F] = ...
```
to
```scala
trait ConsoleFx[F[*]] {
def readLn(implicit fxCtor: FxCtor[F]): F[String]
def readPassword(implicit fxCtor: FxCtor[F]): F[Array[Char]]
def …
```

effectie v2.0.0-beta8

---

docs/latest/cats-effect2/cats-effect2.md
docs/latest/cats-effect2/console-fx.md
docs/latest/monix3/monix3.md
website/docusaurus.config.js
website/src/pages/versions.js

Update: docs - to comply with the latest effectie (`ConsoleEffect` => `ConsoleFx` and no more `instances.console`) / the latest effectie version info

Update: docs - to comply with the latest effectie (ConsoleEffect => ConsoleFx and no more instances.console) / the latest effectie version info

---

build.sbt

Close #513 - Remove `cats` from the `core` module

Close #513 - Remove `cats` from the `core` module

---

modules/effectie-core/shared/src/main/scala/effectie/core/FromFuture.scala
modules/effectie-core/shared/src/main/scala/effectie/instances/tries/fx.scala

Fix the name of `object` extending `FxOfTry` / Make `FromFutureToIdTimeout` and `FromFutureToTryTimeout` value classes

Fix the name of `object` extending `FxOfTry` / Make `FromFutureToIdTimeout` and `FromFutureToTryTimeout` value classes

---

modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2ResourceMaker.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/resource/Ce2ResourceMakerSpec.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3ResourceMaker.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/resource/Ce3ResourceMakerSpec.scala

Close #530 - Rename `withResource` in `Ce2ResourceMaker` and `Ce3ResourceMaker` to `maker`

Close #530 - Rename `withResource` in `Ce2ResourceMaker` and `Ce3ResourceMaker` to `maker`

---

modules/effectie-core/shared/src/main/scala/effectie/resource/ResourceMaker.scala

Close #529 - Remove unnecessary re-evaluation of `ResourceMaker`

Close #529 - Remove unnecessary re-evaluation of `ResourceMaker`

---

changelogs/2.0.0-beta10.md
version.sbt

* Add `fromEffect(fa: => F[A]): F[A]` to `FxCtor` and `Fx` (#524)
```scala
Fx[IO].fromEffect(IO(1)) // IO[Int]
FxCtor[IO].fromEffect(IO(1)) // IO[Int]
```
* Add `make[A](fa: => F[A])(release: A => F[Unit]): ReleasableResource[F, A]` to `ResourceMaker[F[*]]` (#527)
```scala
def make[A](fa: => F[A])(release: A => F[Unit]): ReleasableResource[F, A]
```
* `Try`
```scala
val resourceMaker = ResourceMaker.usingResourceMaker
resourceMaker
.make(Try(new SomeResource()))(a => Try(a.release())) // ReleasableResource[Try, SomeResource]
.use { someResource =>
// do something with someResource
Try(result) // Try[ResultType]
} // Try[ResultType]
```
* Future
```scala
val resourceMaker = ResourceMaker.futureResourceMaker
resourceMaker
.make(Future(new SomeResource()))(a => Future(a.release())) // …
```

effectie v2.0.0-beta10

---

.github/workflows/release.yml

Update: GitHub Actions - no more binary file (jar) upload to GitHub release

Update: GitHub Actions - no more binary file (jar) upload to GitHub release

---

modules/effectie-cats-effect2/shared/src/main/scala/effectie/resource/Ce2ResourceMaker.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/resource/Ce3ResourceMaker.scala

Close #559 - Fix the comments of the `deprecated` methods in `Ce2ResourceMaker` and `Ce3ResourceMaker`

Close #559 - Fix the comments of the `deprecated` methods in `Ce2ResourceMaker` and `Ce3ResourceMaker`

---

changelogs/2.0.0-beta11.md
version.sbt

* Fix the comments of the `deprecated` methods in `Ce2ResourceMaker` and `Ce3ResourceMaker` (#559)
* `Ce2ResourceMaker`: `Please use withResource instead` => `Please use Ce2ResourceMaker.maker instead`
* `Ce3ResourceMaker`: `Please use withResource instead` => `Please use Ce3ResourceMaker.maker instead`

effectie v2.0.0-beta11

---

modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/canCatch.scala
modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/canHandleError.scala
modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/canRecover.scala
modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/fromFuture.scala
modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/fx.scala
modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/fxCtor.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/canCatchSpec.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/canHandleErrorSpec.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/canRecoverSpec.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/fromFutureSpec.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/fxCtorSpec.scala
modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/f/fxSpec.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/canCatch.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/canHandleError.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/canRecover.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/fromFuture.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/fx.scala
modules/effectie-cats-effect3/shared/src/main/scala/effectie/instances/ce3/f/fxCtor.scala
modules/effectie-cats-effect3/shared/src/test/scala-3/effectie/instances/ce3/testing/IoAppUtils.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/canCatchSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/canHandleErrorSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/canRecoverSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/fromFutureSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/fxCtorSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/f/fxSpec.scala

Close #568 - Add instances of `CanCatch`, `CanHandleError`, `CanRecover`, `FromFuture`, `Fx` and `FxCtor` with `Sync` and `Async`

Close #568 - Add instances of `CanCatch`, `CanHandleError`, `CanRecover`, `FromFuture`, `Fx` and `FxCtor` with `Sync` and `Async`

---

changelogs/2.0.0-beta12.md
version.sbt

* Add `CanRestart` for retrying `F[A]` (#566)
```scala
trait CanRestart[F[*]] {
def restartWhile[A](fa: F[A])(p: A => Boolean): F[A]
def restartUntil[A](fa: F[A])(p: A => Boolean): F[A]
def restartOnError[A](fa: F[A])(maxRetries: Long): F[A]
def restartOnErrorIfTrue[A](fa: F[A])(p: Throwable => Boolean): F[A]
}
```
* Add instances of `CanCatch`, `CanHandleError`, `CanRecover`, `FromFuture`, `Fx` and `FxCtor` with `Sync` and `Async` (#568)
So it can be done like this with the `effectie.instances.ce2.f` and `effectie.instances.ce3.f` packages.
```scala
def foo[F[*]: Fx](n: Int): F[Int] = Fx[F].effectOf(n * 2)
// Fx[F] can be satisfied with just Sync[F] like this.
import effectie.instances.ce2.f.fx._
def bar[F[*]: Sync](n: Int): F[Int] = foo(n)
```

effectie v2.0.0-beta12

---

modules/effectie-cats-effect2/shared/src/test/scala/effectie/instances/ce2/CanRestartSpec.scala
modules/effectie-cats-effect3/shared/src/test/scala/effectie/instances/ce3/CanRestartSpec.scala

Add heavy recursion tests for `CanRestart` (with 1,000,000 times of recursive calls)

Add heavy recursion tests for `CanRestart` (with 1,000,000 times of recursive calls)

---

modules/effectie-core/shared/src/main/scala/effectie/instances/future/canHandleError.scala
modules/effectie-core/shared/src/main/scala/effectie/instances/future/canRecover.scala

Fix #584 - Make sure error handling for `Future` uses `Future`'s error handling methods

Fix #584 - Make sure error handling for `Future` uses `Future`'s error handling methods

---

modules/effectie-core/shared/src/main/scala/effectie/instances/tries/canHandleError.scala
modules/effectie-core/shared/src/main/scala/effectie/instances/tries/canRecover.scala

Close #586 - `CanHandleError[Try].handleNonFatal` and `CanRecover[Try].recoverFromNonFatal` should use `Try`'s `recover`

Close #586 - `CanHandleError[Try].handleNonFatal` and `CanRecover[Try].recoverFromNonFatal` should use `Try`'s `recover`

---

modules/effectie-syntax/shared/src/main/scala-2/effectie/syntax/error.scala
modules/effectie-syntax/shared/src/main/scala-3/effectie/syntax/error.scala
modules/effectie-syntax/shared/src/test/scala-2/effectie/syntax/errorSpec.scala
modules/effectie-syntax/shared/src/test/scala-3/effectie/syntax/errorSpec.scala

Close #588 - `rethrowIfLeft` and `rethrowTIfLeft` syntax for `F[Either[A, B]]` and `EitherT[F, A, B]`

Close #588 - `rethrowIfLeft` and `rethrowTIfLeft` syntax for `F[Either[A, B]]` and `EitherT[F, A, B]`

---

changelogs/2.0.0-beta13.md
version.sbt

* `CanHandleError[Future]` and `CanRecover[Future]` should use `Future`'s `recover` and `recoverWith`. (#584)
* `CanHandleError[Try].handleNonFatal` and `CanRecover[Try].recoverFromNonFatal` should use `Try`'s `recover` (#586)
* `rethrowIfLeft` and `rethrowTIfLeft` `syntax` for `F[Either[A, B]]` and `EitherT[F, A, B]` (#588)
```scala
val fa: IO[Either[Throwable, Int]] = pureOf[IO](Right(1))
fa.rethrowIfLeft
// IO[Int] = IO(1)
```
```scala
val fa: IO[Either[Throwable, Int]] = pureOf[IO](Left(new RuntimeException("Error")))
fa.rethrowIfLeft
// IO[Int] = RaiseError(RuntimeException("ERROR"))
```
```scala
val fa: EitherT[IO, Throwable, Int] = pureOf[IO](Right(1)).eitherT
fa.rethrowTIfLeft
// IO[Int] = IO(1)
```
```scala
val fa: EitherT[IO, Throwable, Int] = pureOf[IO](Left(new …
```

effectie v2.0.0-beta13

---

build.sbt

Close #601 - Add `effectie-time` module

Close #601 - Add `effectie-time` module

---

modules/effectie-time/shared/src/main/scala/effectie/time/ApproxFiniteDuration.scala
modules/effectie-time/shared/src/main/scala/effectie/time/syntax.scala
modules/effectie-time/shared/src/test/scala/effectie/time/ApproxFiniteDurationSpec.scala
modules/effectie-time/shared/src/test/scala/effectie/time/syntaxSpec.scala

Close #603 - [`effectie-time`] Add `ApproxFiniteDuration` and `syntax`

Close #603 - [`effectie-time`] Add `ApproxFiniteDuration` and `syntax`

---

modules/effectie-time/shared/src/main/scala/effectie/time/TimeSource.scala
modules/effectie-time/shared/src/main/scala/effectie/time/syntax.scala
modules/effectie-time/shared/src/test/scala/effectie/time/TimeSourceSpec.scala
modules/effectie-time/shared/src/test/scala/effectie/time/syntaxSpec.scala

Close #602 - [`effectie-time`] Add `TimeSource`

Close #602 - [`effectie-time`] Add `TimeSource`

---

changelogs/2.0.0-beta14.md
version.sbt

* Add `effectie-time` module (#601)
* [`effectie-time`] Add `TimeSource` (#602)
```scala
TimeSource[F].currentTime()
TimeSource[F].realTime
TimeSource[F].realTimeTo
TimeSource[F].monotonic
TimeSource[F].monotonicTo
TimeSource[F].timeSpent(F[A])
```
* [`effectie-time`] Add `ApproxFiniteDuration` and `syntax` (#603)
```scala
import scala.concurrent.duration._
import effectie.time.syntax._
5.seconds +- 2.seconds
// ApproxFiniteDuration(5.seconds, 2.seconds)
3.seconds.isWithIn(5.seconds +- 2.seconds)
// Boolean = true
7.seconds.isWithIn(5.seconds +- 2.seconds)
// Boolean = true
2.seconds.isWithIn(5.seconds +- 2.seconds)
// Boolean = false
8.seconds.isWithIn(5.seconds +- 2.seconds)
// Boolean = false
```
* Add ~~`effectie-cats-effect2-time`~~ `effectie-time-cats-effect2` (#607)
* …

effectie v2.0.0-beta14

---

changelogs/2.0.0.md

* Temporarily disable `Scala.js` support (#636)
* Improve design (Effectie v2) (#300)
It also includes all the changes in the following releases.
* Make `Fx` `CanCatch` (#301)
* Make `Fx` `CanHandleError` (#302)
* Make `Fx` `CanRecover` (#303)
* `core` project should be effect library free (#304)
* Sub-projects for `Cats Effect` and `Monix` (#305)
* Remove `EffectConstructor` (#306)
* Withdraw `Scalaz Effect` support (#308)
* Remove `Xor` (#310)
* Remove `OptionTSupport` (#314)
* Remove `EitherTSupport` (#315)
* Remove `Fx`, `FxCtor` and `CanCatch` `trait`s from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix` (#320)
* Remove `CanHandleError` and `CanRecover` `trait`s from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix` (#322)
* Add missing type …

effectie v2.0.0

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/manual-build.yml
.github/workflows/release.yml

Update GitHub Actions configuration to use `sbt/setup-sbt` action and simplify caching for sbt

Update GitHub Actions configuration to use `sbt/setup-sbt` action and simplify caching for sbt

---

modules/effectie-cats-effect2/shared/src/main/scala/effectie/instances/ce2/f/fxCtor.scala

Close #658: Update `effectie.instances.ce2.f.fxCtor.syncFxCtor.pureOrError` for consistency

Close #658: Update `effectie.instances.ce2.f.fxCtor.syncFxCtor.pureOrError` for consistency
